tamagui/tamagui

packages/tamagui/src/views/Group.tsx

fix: missing React on `Group` component (fixes #66)

---

apps/site/data/docs/core/styled.mdx

Minor typo

---

apps/site/data/docs/intro/themes.mdx

updates themes.mdx

---

apps/site/data/docs/core/use-media.mdx

use-media.mdx

---

apps/site/data/docs/core/configuration.mdx

- Added a fix to the core configuration page, correcting:
"The you'll just want to bring along any fonts..." -> "Then you'll just want to bring along any fonts..."

fix(site): fixed typo

---

apps/starter/packages/config/tamagui.config.ts
packages/config-base/src/tamagui.config.ts
packages/config-default-node/src/index.ts
packages/core-node/types/helpers/themeable.d.ts
packages/core-node/types/hooks/useTheme.d.ts
packages/core-node/types/types.d.ts
packages/core/src/createComponent.tsx
packages/core/src/createTamagui.ts
packages/core/src/hooks/useTheme.tsx
packages/core/src/types.tsx
packages/core/src/views/TamaguiProvider.tsx
packages/core/types/helpers/themeable.d.ts
packages/core/types/hooks/useTheme.d.ts
packages/core/types/types.d.ts

not necessary with defaultTheme on ThemeProvider

fix(core): Remove defaultTheme property on createTamagui()

---

packages/sheet/src/SheetScrollView.tsx

I was looking at the code an noticed this spelling error.
I understand it is a very small commit and of not much value but still...

Fix tiny spelling mistake

---

packages/select/src/Select.tsx

use SizableText instead of Paragraph for SelectItemText

---

apps/site/data/docs/guides/expo.mdx

docs: upgrade archived link for starter

---

apps/site/data/docs/intro/themes.mdx

https://tamagui.dev/docs/guides/create-tamagui does not exist
changed to: https://tamagui.dev/docs/guides/create-tamagui-app

Link error

---

README.md
apps/site/data/blog/version-one.mdx
apps/site/data/docs/components/alert-dialog/1.0.0.mdx
apps/site/data/docs/components/dialog/1.0.0.mdx
apps/site/data/docs/components/select/1.0.0.mdx
apps/site/data/docs/components/sheet/1.0.0.mdx
apps/site/data/docs/components/slider/1.0.0.mdx
apps/site/data/docs/components/text/1.0.0.mdx
apps/site/data/docs/components/unspaced/1.0.0.mdx
apps/site/data/docs/core/variants.mdx
apps/site/data/docs/guides/next-js.mdx
apps/site/data/docs/intro/compiler-install.mdx
apps/site/data/docs/intro/introduction.mdx
apps/site/data/docs/intro/props.mdx
packages/core-node/types/hooks/useMedia.d.ts
packages/core/src/hooks/useMedia.tsx
packages/core/src/types.tsx
packages/core/types/hooks/useMedia.d.ts
packages/create-themes/src/createThemes.ts

Think most of theme are resolved! Did this while taking a deep dive into the code/docs.

fix docs typos

---

packages/create-tamagui/src/index.ts

Add option to inicialize GIT in the project

feat(create-tamagui): Prompt for git init

---

apps/site/data/docs/components/sheet/1.0.0.mdx

Document `Scrollview` in `Sheet` docs

chore: document `Scrollview` in `Sheet` docs

---

apps/site/data/docs/guides/create-tamagui-app.mdx

docs: update create-tamagui-app dep versions

---

packages/button/src/Button.tsx

1. it had wrong default value
2. it had two separate comments - I merged them

fix: jsdoc wrong default value for button prop

---

packages/web/src/createComponent.tsx

fix(core): onClick exist only on web #599

---

apps/site/pages/404.tsx

fix(site): fix color text 404 page #624

---

packages/use-window-dimensions/src/index.ts

There's no reason to double render here on web

fix: native double render

---

apps/site/data/docs/guides/expo.mdx

The current guide for Expo is a couple of links to projects.  I wanted to add a fairly simple copy / paste command guide to help people get going faster.

Make using Tamagui with Expo easier

---

packages/tamagui/src/views/Group.tsx

fix(group): scrollable bug

---

apps/site/components/Footer.tsx
apps/site/components/Header.tsx
apps/site/components/MediaPlayer.tsx
apps/site/components/SponsorButton.tsx
apps/site/pages/_document.tsx
apps/site/pages/index.tsx
packages/logo/src/TamaguiLogo.tsx

minor improvements to increase the PageSpeed SEO and accessibility score

docs(site): improve SEO

---

.github/workflows/changelog.yml
.github/workflows/release.yaml

Should fix CI pipeline from failed 1.7.x releases.

build: upgrade ubuntu18 to ubuntu latest

---

packages/tabs/src/Tabs.tsx
packages/tabs/types/Tabs.d.ts

fix(tabs): conditional tab trigger `onInteraction` issue

---

apps/site/data/docs/components/list-item/1.0.0.mdx

- previously included Button props. Updated names, etc.
- added extra docs on what's possible to customize to save a user time
- added an extra clarification on ListItemFrame
Thank you!

Docs: Fixes, Clarifies & Updates ListItem customization docs

---

apps/site/data/docs/components/sheet/1.0.0.mdx

Put  <Sheet.Handle /> out of  <Sheet.Frame>

Fixed Sheets example;  <Sheet.Handle /> out of  <Sheet.Frame>

---

packages/sheet/src/Sheet.tsx

see https://discord.com/channels/909986013848412191/994937898908516362/1081409443457138748

fix(sheet): not change render on rezise sheet

---

apps/site/data/docs/guides/vite.mdx

not sure if this is the correct example to link to, but from the list of apps this one seems to be the correct one :)

Update Vite guide example link

---

apps/site/pages/docs/components/[...slug].tsx

fix(site): adding version to page removes fragment

---

apps/sandbox/Sandbox.tsx
packages/core-test/getSplitStyles.web.test.tsx
packages/helpers/src/validStyleProps.ts
packages/helpers/types/validStyleProps.d.ts
packages/static-tests/tests/__snapshots__/babel.test.tsx.snap
packages/web/src/helpers/createPropMapper.ts
packages/web/src/helpers/getSplitStyles.tsx

Closes #845 
Ignore the branch name... [the plan changed along the way](https://github.com/tamagui/tamagui/issues/845#issuecomment-1486860978).

fix(core): make font props work independently

---

apps/site/data/docs/components/sheet/1.9.18.mdx
packages/sheet/src/Sheet.tsx
packages/sheet/src/types.tsx
packages/sheet/types/Sheet.d.ts
packages/sheet/types/types.d.ts

Fixes issues of several users who mentioned this on the Discord server

feat(sheet): new `moveOnKeyboardChange` prop

---

packages/alert-dialog/src/AlertDialog.tsx
packages/dialog/src/Dialog.tsx
packages/dialog/types/Dialog.d.ts
packages/sheet/src/Sheet.tsx
packages/sheet/types/Sheet.d.ts

fix(dialog,alert-dialog,sheet): consistent overlay

---

packages/core-test/createTamagui.web.test.tsx
packages/core-test/getSplitStyles.web.test.tsx
packages/web/src/createTamagui.ts
packages/web/src/helpers/createPropMapper.ts

Fixes:
- z-index getting units 
- z-index resolving to space variables

fix(core): z-index bugs

---

packages/tamagui/src/views/Input.tsx
packages/tamagui/types/views/Input.d.ts
packages/web/src/types.tsx
packages/web/types/types.d.ts

Preferably to be merged after https://github.com/tamagui/tamagui/blob/764b7703c6f3d8c2e4b4117a6194dbe574192902/next.md?plain=1#L30 is in place

feat(input): add outline on focusStyle and remove negative margin

---

apps/sandbox/Sandbox.tsx
next.md
packages/web/src/createComponent.tsx
packages/web/src/styled.tsx
packages/web/types/styled.d.ts

fix(web): fix styled() + focusStyle + input nested styling not applying

---

apps/sandbox/Sandbox.tsx
packages/web/src/helpers/getSplitStyles.tsx
packages/web/src/styled.tsx

Fixes https://github.com/tamagui/tamagui/issues/934

fix(web): fix use className on HOC components when possible, fixing merge issue with pseudo styles in variants

---

apps/kitchen-sink/src/features/user/demo-screen.tsx
packages/web/src/helpers/getSplitStyles.tsx

fix(web): remove outline styles form native

---

packages/react-native-web-lite/src/TextInput/index.tsx
packages/react-native-web-lite/src/TextInput/types.tsx

updated text input based on the latest changes in React Native Web
[ReactNativeWeb:TextInput](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/TextInput/index.js)

fix: TextInput some missing, and deprecated props

---

apps/site/data/docs/components/toast/1.15.15.mdx
packages/toast/src/Toast.tsx
packages/toast/src/ToastImperative.tsx
packages/toast/types/Toast.d.ts
packages/toast/types/ToastImperative.d.ts

Added docs as 1.15.15 assuming that's the release version for this.

feat(toast): flattened custom fields, ts module augmentation support

---

apps/sandbox/Sandbox.tsx

Small fix since the sandbox for vite seems to be broken for me (and probably others?)

Change sandbox to use lazy imports and Suspense to allow vite to work

---

next.md

fix typo in next.md

---

starters/next-expo-solito/apps/expo/package.json
starters/next-expo-solito/package.json
starters/next-expo-solito/yarn.lock

Fixes https://github.com/tamagui/tamagui/issues/1043

fix(starter): react-native-svg version ver causing error on android

---

apps/site/data/docs/components/dialog/1.0.0.mdx

remove duplicated prop of `trapFocus`

Update Dialog prop to remove duplicated trapFocus

---

apps/site/components/BlogSlugPage.tsx

fix(blog): post page date format

---

packages/sheet/src/Sheet.tsx
packages/sheet/src/useSheetChildren.tsx
packages/sheet/types/useSheetChildren.d.ts

Caused after #957
https://user-images.githubusercontent.com/35243344/235455201-6a8c8ad1-8843-40fb-8ba2-7a1bd9c240cd.mov

fix(sheet): behind being visible when dragged up

---

apps/site/components/SupabaseProvider.tsx

site: possible fix for auth issue on subdomain

---

apps/site/data/docs/intro/installation.mdx

Fix typo in docs (installation.mdx)

---

apps/site/data/docs/core/configuration.mdx

fix typo in typography docs

---

packages/demos/src/ToastDemo.tsx
packages/demos/src/ToastDuplicateDemo.tsx
packages/demos/types/ToastDemo.d.ts
packages/demos/types/ToastDuplicateDemo.d.ts

docs(toast): add note on demos for ToastViewport

---

apps/site/data/docs/guides/next-js.mdx

docs: remove minimal next.js config section

---

starters/next-expo-solito/turbo.json

https://turbo.build/repo/docs/reference/configuration#globalenv
Been using the starter and made a small quality-of-life improvement.

add glbal env to turbo

---

starters/next-expo-solito/turbo.json

fast follow from 
https://github.com/tamagui/tamagui/pull/1166#discussion_r1195450655
remove globalEnv from pipeline

remove from pipeline

---

packages/checkbox/src/Checkbox.tsx
packages/checkbox/types/Checkbox.d.ts

also fixes default size being undefined (checkbox being having 0 width/height)

feat(checkbox): use `createStyleContext` API

---

apps/site/data/docs/guides/how-to-build-a-button.mdx

Hi, thanks natew for this guide, it shows various ways to use tamagui styled system, it's really helpful.
There was juste a 404 on the link to tamagui config file in starter.
Thanks for your work

fix(docs): link to tamagui config

---

README.md

https://discord.com/channels/909986013848412191/994937898908516362/1108420725976612904
was getting invalid character issue too. ran `yarn watch:build` without issue

(docs) update readme build step

---

apps/site/data/docs/core/variants.mdx

fix(docs): typo on core/variants

---

starters/next-expo-solito/.gitignore

ignore auto generated build logs turbo repo

add ignore for turbo build

---

apps/site/data/docs/core/animations.mdx

https://github.com/tamagui/tamagui/blob/master/packages/config/src/animations.ts#L3
fix type error, config is bouncy.

fix typo, bounce is invaid in config

---

package.json
yarn.lock

run `npx @turbo/codemod update`

bump turbo

---

packages/web/src/constants/accessibilityDirectMap.native.tsx
packages/web/src/helpers/getSplitStyles.tsx

would fix the failing test after merge + release

fix(web): `accessibilityRole` not overwriting `role`

---

packages/demos/src/GroupDemo.tsx

type warning to use orientation, updated theprop to use orientation instead of axis

fix group docs

---

starters/next-expo-solito/package.json
starters/next-expo-solito/yarn.lock

upgrade to latest
test:
- run turbo build
- run turbo dev
- run yarn native
all commands running as expected

chore: bump turbo

---

apps/site/data/docs/guides/next-js.mdx

Fix spelling

---

packages/cli/src/add.ts

Closes https://github.com/tamagui/unistack/issues/16

fix(cli): note on navigating the autocomplete prompt

---

apps/site/pages/community.tsx

Simple PR adding create-t4-app to the Community Page

Add create-t4-app to Community page

---

apps/site/data/docs/intro/themes.mdx

Update themes.mdx - minor typo

---

apps/site/data/docs/guides/expo.mdx

This adds the changes needed to play well with metro for expo web support.

[Docs] Expo Web Support with Metro Change

---

apps/kitchen-sink/src/Sandbox.tsx
packages/web/src/hooks/useMedia.tsx

Fine on web; only an issue on native.

ix(core): media not working properly on native

---

apps/site/app.css
apps/site/lib/getProductInfo.ts
apps/site/pages/api/discord/channel.ts
apps/site/pages/takeout.tsx

site: license details table

---

apps/site/data/docs/guides/design-systems.mdx

Yo 👋 
Fixing a small typo on docs

Fix small typo on DS docs

---

apps/site/data/docs/components/stacks/1.0.0.mdx
apps/site/data/docs/core/configuration.mdx
apps/site/data/docs/core/styled.mdx
apps/site/data/docs/core/theme.mdx
apps/site/data/docs/core/use-media.mdx
apps/site/data/docs/guides/developing.mdx
apps/site/data/docs/guides/how-to-build-a-button.mdx
apps/site/data/docs/intro/themes.mdx
apps/site/pages/talk/slides/slide-core-features.tsx
apps/site/pages/talk/slides/slide-web-only.tsx
packages/web/src/hooks/useMedia.tsx
packages/web/src/styled.tsx

I implemented tamagui into my latest project. 
While reading through the docs I found a few typos, so I made a PR to fix them.

docs: ✏️ Fix various typos in the docs

---

packages/helpers/package.json
yarn.lock

fix: add @tamagui/constants to the deps list of @tamagui/helpers

---

packages/create-tamagui/package.json
packages/create-tamagui/src/helpers/cloneStarter.ts
yarn.lock

Fixes https://github.com/tamagui/unistack/issues/80

fix(create-tamagui): failing on windows due to `rm`

---

packages/web/src/createTamagui.ts

Issue reported by @nandorojo on Discord

fix(web): specific tokens not working on native

---

packages/web/src/config.ts

fix(web): add note on version conflict on getConfig error

---

apps/kitchen-sink/src/usecases/GroupUseCases.tsx
apps/kitchen-sink/tests/GroupUseCases.test.tsx
apps/site/data/docs/components/group/1.56.1.mdx
packages/group/src/Group.tsx
packages/group/types/Group.d.ts

feat(group): new `forcePlacement` prop on `Group.Item`

---

packages/web/src/helpers/getSplitStyles.tsx
packages/web/src/views/Text.tsx

Fixes #1536 Creating selectable text

fix(core): `selectable` not working on `<Text>` as expected

---

packages/themes/package.json
packages/web/src/views/Theme.tsx

fix(core): sheet not getting the right theme when used in a component with component theme definitions

---

packages/switch/src/createSwitch.tsx
packages/switch/types/createSwitch.d.ts

this was exposed in prev versions so technically breaking change

fix(switch): export `SwitchProps`

---

apps/site/data/docs/components/sheet/1.59.0.mdx

docs(sheet): document snapPointsMode prop

---

packages/create-tamagui/integration.test.ts
packages/create-tamagui/src/index.ts

Closes https://github.com/tamagui/unistack/issues/13

feat(create-tamagui): change root package.json name to project name

---

packages/create-tamagui/src/steps/takeout.ts

related: https://github.com/tamagui/unistack/pull/134

docs(create-tamagui): update native instructions for takeout 

---

packages/select/src/SelectItem.tsx

fix(SelectItem): not working on touchable devices web

---

apps/site/data/docs/core/configuration.mdx

just had replaced the name of file which were incorrect in the URL. 
for `Source` URL => ''..../src/tamagui.config.ts" 
which is replaced to => "'..../src/config.ts"
for `Output` URL=> "'..../type/tamagui.config.ts" 
which is replaced to => "'..../type/config.ts"

Fixed File not found Error Github Page, Updated configuration.mdx

---

apps/site/data/docs/core/configuration.mdx

Related Discord thread: https://discord.com/channels/909986013848412191/1156957761700110356

docs: add note on metro's `isCSSEnabled`

---

CONTRIBUTING.md

fix small typo in contributing.md

---

CONTRIBUTING.md

move: It's a bit of a context switch between trying to setup something technical, reading non-technical rules, then switching back.
Obviously, subjective. Feel free to close PR if not needed.

move install next to ui kit

---

packages/create-tamagui/integration.test.ts
packages/create-tamagui/src/helpers/cloneStarter.ts
packages/create-tamagui/src/index.ts

change logs to infos

---

packages/button/src/Button.tsx
packages/create-tamagui/integration.test.ts
packages/create-tamagui/src/helpers/cloneStarter.ts
packages/create-tamagui/src/index.ts

button typo

---

apps/site/data/docs/core/configuration.mdx

typo, inversing not word

---

packages/demos/src/SheetDemo.tsx

has fit isn't used

---

CONTRIBUTING.md
packages/tooltip/src/Tooltip.tsx

add port link to contribution docs

---

packages/tamagui/package.json
packages/web/package.json

Hope this will help with Depenabot release notes
Fixes stale reference in packages/web

Add git repository reference to tamagui package

---

.github/ISSUE_TEMPLATE/bug.yml

make bug report friendly

---

.github/ISSUE_TEMPLATE/bug.yml

yaml formatting

---

.github/ISSUE_TEMPLATE/bug.yml
README.md

a bit more terse, less is more

simplify readme

---

.github/ISSUE_TEMPLATE/bug.yml

There is a problem with this template
Description must be between 3 and 200 characters. Learn more about this error.
seeing this error in gh now, didn't know there's a character limit.

bug template too long

---

.github/ISSUE_TEMPLATE/bug.yml

error still exists. sorry for the back and forth

still too long

---

.github/ISSUE_TEMPLATE/bug.yml

another fix
tried previewing bug template with code changes here, they're unfortunately not reflecting changes. Sorry this is a bit of spaghetti throwing.

bug template fix

---

packages/linear-gradient/tsconfig.json

quick format change from prettier.

small format, linear grad

---

.github/ISSUE_TEMPLATE/bug.yml
CONTRIBUTING.md

* update docs
* bug template fix (#1858)

update docs (#1856)

---

apps/kitchen-sink/src/App.native.tsx

remove unused imports

---

CONTRIBUTING.md

took @natew 's reply https://github.com/tamagui/tamagui/issues/1877 updated the docs

update contribution with expo context

---

packages/web/src/types.tsx

bunch of typos

---

packages/popper/src/Popper.tsx

typos in popper

---

packages/web/src/hooks/useMedia.tsx

Fixed: useMedia initial value is always false native

fix(useMedia): wrong initial value native

---

packages/demos/src/SelectDemo.tsx

Update type in Select Demo

---

packages/web/src/index.ts
packages/web/types/index.d.ts

fix https://github.com/tamagui/tamagui/discussions/1958

fix(internalWithTheme): not exported

---

apps/site/data/docs/components/select/1.40.0.mdx
packages/select/src/SelectContent.tsx
packages/select/src/SelectImpl.tsx

fix(Select): content shouldn't be scrollable when fully visible

---

packages/web/src/hooks/useProps.tsx

update doc comment return type

update docs for usePropsAndStyle

---

CONTRIBUTING.md

grabbed content from here: https://discord.com/channels/909986013848412191/1107796041014706186/1107796128654708776

update contribution docs

---

packages/checkbox/src/Checkbox.tsx
packages/popover/src/Popover.tsx

fix(nested Presence): checkbox nested inside PopoverContent

---

packages/web/src/createComponent.tsx

fix(tag prop): tag ignored when there is animation prop

---

packages/core/reset.css
packages/web/reset.css

Found out that I added the reset css to the wrong place and only found out due to me starting a new tamagui project.
Not sure what to do about the @tamagui/web file.

reset.css reserve width for vertical scrollbars

---

packages/loader/src/TamaguiPlugin.ts
packages/loader/types/TamaguiPlugin.d.ts
packages/types/types.d.ts

Make the Tamagui Webpack plugin to output one CSS file, this will improve performance.

feat(TamaguiPlugin): output one css file initial version

---

packages/popover/src/Popover.tsx

fix(Popover): trap focus

---

packages/stacks/src/Stacks.tsx
packages/web/src/views/Configuration.tsx
packages/web/src/views/FontLanguage.native.tsx
packages/web/src/views/FontLanguage.tsx
packages/web/src/views/Slot.tsx
packages/web/src/views/Stack.tsx
packages/web/src/views/TamaguiProvider.tsx
packages/web/src/views/Text.tsx
packages/web/src/views/Theme.tsx
packages/web/src/views/ThemeDebug.native.tsx
packages/web/src/views/ThemeDebug.tsx
packages/web/src/views/View.tsx

Fixes https://github.com/tamagui/takeout/issues/179

fix(web): add missing component display names

---

packages/create-tamagui/src/helpers/cloneStarter.ts
packages/create-tamagui/src/templates.ts

Fixes https://github.com/tamagui/takeout/issues/230

fix(create-tamagui): SSH fallback cloning not working properly

---

packages/static/src/extractor/createExtractor.ts

fix https://github.com/tamagui/tamagui/issues/1694

fix(compiler:web): make media query to work inside styled

---

packages/button/src/Button.tsx

fix(Button): convert to <a/> tag when role=link in styled

---

apps/site/data/docs/components/toast/1.15.15.mdx
packages/toast/src/ToastViewport.tsx
packages/toast/types/ToastViewport.d.ts

feat(toast): add portal support

---

packages/web/src/createComponent.tsx

fix(input:native): focusStyle not applying

---

packages/animations-moti/src/createAnimations.tsx

fix(moti): don't use css vars

---

packages/sheet/src/createSheet.tsx

fix(sheet): make modal by defaul false when native ios

---

packages/popper/src/Popper.tsx

fix(popper): broken when rtl

---

packages/dialog/src/Dialog.tsx

fix(dialog): trapfocus

---

packages/select/src/SelectImpl.tsx

fix(select): make it to open with spacebar

---

.vscode/extensions.json

we use `biome check` to check the formatting of the code and using other tools (e.g. prettier) will not result in the same code. the Biome vscode extension should help

chore: add biome to workspace's recommended extensions (vscode)

---

apps/site/data/docs/core/configuration.mdx
packages/popover/src/Popover.tsx

fix-config-typo-docs

---

packages/cli/src/cli.ts
packages/cli/src/update-template.ts
packages/cli/types/update-template.d.ts

can be used to update a repo with a template (e.g. Takeout)

feat(cli): the `update-template` command

---

packages/web/src/createComponent.tsx

fix(core): disabled prop not applying

---

packages/babel-plugin/src/index.ts
packages/static-tests/tests/__snapshots__/babel.native.test.tsx.snap
packages/static-tests/tests/__snapshots__/flatten.native.test.tsx.snap

- Fix the Closing Tag not syncing with the opening Tag
- use theme.[token].val instead of theme.[token]

fix(compiler:native): fix some bugs with expermentalThemeFlatening

---

packages/toggle-group/src/ToggleGroup.tsx
packages/toggle-group/types/ToggleGroup.d.ts

fix(ToggleGroup): invalid dom props

---

packages/popper/src/Popper.tsx

fix(popper:native): position issue

---

apps/site/pages/bento.tsx

note: visual cue for vertical scroll items that are hidden

bento: style: add bg for bento card items on mobile

---

packages/babel-plugin/src/index.ts
packages/static-tests/tests/__snapshots__/babel.native.test.tsx.snap
packages/static-tests/tests/__snapshots__/flatten.native.test.tsx.snap
packages/static-tests/tests/__snapshots__/webpack.test.tsx.snap
packages/static/src/extractor/createExtractor.ts
packages/web/src/helpers/getSplitStyles.tsx
packages/web/src/helpers/propMapper.ts
packages/web/src/types.tsx
packages/web/types/helpers/getSplitStyles.d.ts
packages/web/types/types.d.ts

fix(compiler:native): some issues style order

---

starters/simple-web/package.json
starters/simple-web/yarn.lock

fix(vite starter): add missing expo-linear-gradient depedency

---

apps/site/components/BentoCard.tsx
apps/site/components/DocsPage.tsx
apps/site/components/PropsTable.tsx
apps/site/data/docs/intro/props.mdx
apps/site/tamagui.config.ts

- added deprecated tag to PropsTable
- updated prev/next DocsPage buttons interaction style
- made BentoCard bigger

added missing props

---

apps/site/data/docs/components/visually-hidden/1.0.0.mdx

fix typo in VisuallyHidden 1.0.0.mdx

---

packages/metro-plugin/src/transformer.ts

should fix `expo-router` starter issue on windows
[discord reported issue](https://discord.com/channels/909986013848412191/1226204289626804254)

fix(metro-plugin): windows invalid path

---

apps/site/lib/apiOssBentoRoute.ts
apps/site/pages/api/bento/code/[...slug].tsx

- handle res on catch
- remove production env if statement that was making test against different environments hard.

bento: add missing try catch block to [...slug]

---

packages/demos/src/TabsAdvancedDemo.tsx

- removed deprecated enterVariant & exitVariant of AnimatePresence
- added custom instead

(docs): AdvancedTabsDemo - AnimatePresence update

---

packages/helpers/src/validStyleProps.ts
packages/web/src/helpers/skipProps.ts
packages/web/src/types.tsx
packages/web/types/types.d.ts

feat(core): add scrollbarWidth support

---

packages/sheet/src/createSheet.tsx

fix(sheet): remove unnecessary debug

---

apps/site/data/docs/components/avatar/1.0.0.mdx

This PR fixes the description of Avatar.Image.

doc: Fix Avatar.Image description

---

packages/tamagui/src/views/Input.tsx

fix(Input): remove duplicate focus registration

---

apps/site/components/PurchaseModal.tsx

set to 20 users instead of unlimited

bento: fix copywrite for bento pro plan description

---

packages/accordion/src/Accordion.tsx
packages/accordion/types/Accordion.d.ts
packages/demos/src/AccordionDemo.tsx

add `Accordion.HeightAnimator` for animating the height of the Accordion

feat(Accordion): add height animator

---

packages/demos/src/AccordionDemo.tsx

when copy - pasta example ts error no implicit any
Didn't really wanna touch Accordion because it beta

open is any implicity

---

packages/select/package.json

Move react-dom to peer and dev dependencies

fix react-dom dependency of select

---

packages/select/src/SelectTrigger.tsx

fix: prevent Select Trigger from causing form submission on click

---

apps/site/components/InstallInput.tsx

Update clipboard script in InstallInput.tsx

---

packages/bento-cli/package.json
packages/bento-cli/src/commands/index.tsx
packages/bento-cli/src/components.ts
packages/bento-cli/src/hooks/useGetComponent.tsx
packages/bento-cli/tsconfig.json
packages/bento-cli/types/components.d.ts

bento: bento CLI improvements and fixes

---

.vscode/settings.json
starters/expo-router/app/(tabs)/index.tsx
starters/expo-router/app/(tabs)/two.tsx
starters/expo-router/app/_layout.tsx
starters/expo-router/app/modal.tsx
starters/expo-router/package.json
starters/expo-router/yarn.lock

(starter): expo router ThemeProvider fixes

---

code/ui/sheet/src/SheetImplementationCustom.tsx

fix(sheet): fix sheet max content size on translucent android system ui

---

code/tamagui.dev/data/docs/guides/how-to-build-a-button.mdx

narrow children to correct type in tutorial.

fix buttion tutorial type

---

code/tamagui.dev/app/(site)/account.tsx
code/tamagui.dev/app/(site)/account/items.tsx
code/tamagui.dev/app/api/bento/cli/login+api.ts
code/tamagui.dev/vite.config.ts

Adds a panel for owners of Bento to get an Access Token for use in the next version of `bento-get

feature(bento-get): Accounts/Items Auth-Token Panel

---

code/ui/tamagui/src/views/TextArea.tsx

Fixes https://github.com/tamagui/tamagui/issues/2764
so, I just copied the same that fixed the bug for the Input component. It was merged some time ago.
https://github.com/tamagui/tamagui/pull/2596

fix(TextArea): remove duplicate focus registration

---

scripts/release.ts
scripts/spawnify.ts

- run starter-free tests after upgrade

run starter-free tests in release

---

code/tamagui.dev/data/docs/guides/one.mdx
code/tamagui.dev/features/docs/docsRoutes.tsx

- Add a guide to using Tamagui with One

Add a guide to using Tamagui with One

---

code/compiler/static/src/extractor/bundle.ts
code/compiler/static/types/extractor/bundle.d.ts

fix(static): allow to load .node files

---

code/ooo/data/docs/guides-eas.mdx
code/ooo/data/docs/guides.mdx
code/ooo/data/docs/one-build.mdx

One docs for building and distributing native apps with EAS.

docs(one): EAS

---

code/ui/sheet/src/SheetImplementationCustom.tsx

- Fixes https://github.com/tamagui/tamagui/issues/3024
- Fixes https://github.com/tamagui/tamagui/issues/3071

Sheet: Propagate adapt context

---

code/tamagui.dev/data/docs/core/configuration.mdx

fix(docs): update configuration.mdx

---

code/tamagui.dev/data/docs/components/slider/1.45.0.mdx

Fix: A typo in Slider component documentation

---

code/tamagui.dev/data/docs/components/sheet/1.116.0.mdx

Context: https://discord.com/channels/1223009626400751671/1324372053830402119/1324409980123873300

docs: specify working react-native-ios-modal version

---

code/tamagui.dev/components/LogoCard.tsx

- Removed unnecessary Link wrapper from `LogoCard` component
The document's in-page anchor links to h2 headings were not working properly due to unnecessary wrapper components

fix: refactor LogoCard component to remove unnecessary Link wrapper

---

code/ui/adapt/src/Adapt.tsx

fix(adapt): safely call context methods to prevent potential undefined errors

🐛 Fix: Adapt Context

---

code/tamagui.dev/features/studio/theme/StudioAIBar.tsx

invalid input value check

---

code/demos/src/SheetDemo.tsx

- overlay was showing up as fully opaque

fix: update sheet overlay demo to work with config v4

---

code/tamagui.dev/features/mdx/MDXComponents.tsx

Link was broken.
The full link is https://tamagui.dev/ui/intro

Fix docs UI link

---

code/tamagui.dev/app/api/checkout+api.tsx

Parf of #3182 
Implemented a new feature that allows users to control the auto-renew behavior of their subscriptions. 
- Added code to read the "auto_renew" query parameter (expected values: "true" or "false").
- Determined a flag (cancelAtPeriodEnd) based on the auto_renew value.
- Created the Stripe checkout session in "subscription" mode.
- After creating the session, if cancelAtPeriodEnd is true and a subscription ID is available, the subscription is updated to set cancel_at_period_end to true.

Enable Auto-Renew Option for Stripe Subscriptions via Query Parameter

---

code/tamagui.dev/app/(site)/_layout.tsx
code/tamagui.dev/app/(site)/payment-finished.tsx
code/tamagui.dev/features/site/header/UpgradePopover.tsx
code/tamagui.dev/features/site/purchase/NewAccountModal.tsx
code/tamagui.dev/features/site/purchase/useSubscriptionModal.ts
code/tamagui.dev/features/user/useForwardToDashboard.tsx

account modal

---

code/tamagui.dev/features/site/purchase/StripePaymentModal.tsx
code/tamagui.dev/features/stripe/stripe.ts

The client side wasn't correctly loading environment variables, so I added the VITE_ prefix.

fix to correctyly load env variable

---

code/tamagui.dev/app/api/parity-discount+api.ts
code/tamagui.dev/features/site/purchase/NewPurchaseModal.tsx
code/tamagui.dev/features/site/purchase/useSubscriptionModal.ts
code/tamagui.dev/hooks/useParityDiscount.ts

Display the discount coupon code on the new purchase modal.

---

code/compiler/vite-plugin/src/plugin.ts

fix: Package path resolution broken within @tamagui/vite-plugin on Windows platforms

---

code/tamagui.dev/app/(site)/bento/[...parts]+spa.tsx
code/tamagui.dev/app/(site)/takeout.tsx
code/tamagui.dev/features/pro/ProPolicy.tsx
code/tamagui.dev/features/site/header/PromoCards.tsx
code/tamagui.dev/features/site/header/TooltipLabelLarge.tsx
code/tamagui.dev/features/site/header/UpgradeToProPopover.tsx
code/tamagui.dev/features/site/purchase/BigP.tsx
code/tamagui.dev/features/site/purchase/NewPurchaseModal.tsx
code/tamagui.dev/features/site/purchase/PoliciesModal.tsx
code/tamagui.dev/features/site/purchase/StripePaymentModal.tsx
code/tamagui.dev/features/site/purchase/helpers.tsx

https://github.com/user-attachments/assets/36d0cc73-32b1-4986-8f2f-39f8538d8089

Site: purchase modal

---

code/core/core-test/getSplitStyles.ios.test.tsx
code/core/core-test/getSplitStyles.native.test.tsx
code/core/core-test/getSplitStyles.web.test.tsx
code/core/web/src/helpers/getDynamicVal.ts
code/core/web/src/helpers/getSplitStyles.tsx
code/core/web/src/hooks/getThemeProxied.ts

https://github.com/user-attachments/assets/d0386c0a-1592-48bd-83e5-ba7a352a32e0

fix: theme queries in native

---

code/demos/src/ToastDemo.tsx
code/tamagui.dev/features/studio/ToastProvider.tsx

enhance Toast component with AnimatePresence for improved animations

refactor: Toast #3434

---

code/tamagui.dev/app/api/discord/channel+api.ts
code/tamagui.dev/app/api/discord/support+api.ts
code/tamagui.dev/features/site/purchase/NewAccountModal.tsx
code/tamagui.dev/features/user/helpers.ts
code/tamagui.dev/helpers/ensureSubscription.ts

- Added checks to prevent duplicate Discord channel access for users already subscribed.
- Improved subscription validation by fetching all active subscriptions for better seat calculation.
- Updated Discord channel creation logic to include support for both chat and support tiers.
- Refactored components to streamline the handling of Discord access based on subscription types.
- Enhanced error handling for subscription-related operations, ensuring clearer user feedback.

feat/chat-support: enhance chat support subscription

---

code/tamagui.dev/app/api/bento/cli/v2/code-download+api.ts
code/tamagui.dev/features/bento/hasBentoAccess.ts
code/tamagui.dev/scripts/insert-bento-product-ownership.mjs

- Implemented comprehensive checks for current subscription access to TamaguiPro.
- Added logic to verify legacy lifetime access for users with previous purchases.
- Refactored hasBentoAccess function to streamline access validation and improve clarity.
- Introduced hasLegacyBentoAccess function to handle legacy ownership checks effectively.

feat(bento): enhance access checks for Bento subscriptions and legacy ownership

---

code/core/web/src/createComponent.tsx
code/tamagui.dev/data/docs/core/styled.mdx

refactor(createComponent): enhance ref forwarding logic in styleable

---

code/tamagui.dev/features/docs/docsRoutes.tsx
code/tamagui.dev/features/site/header/Header.tsx

Fixed menu broken on Mobile
Updated section titles

feat(header): add 'Overview' title and update 'Core' section title

---

code/ui/popper/src/Popper.tsx
code/ui/portal/src/Portal.tsx

https://github.com/user-attachments/assets/f16c97d6-de6a-4205-8280-97ac738fabca

fix: resolve DatePicker delays and positioning issues

---

code/tamagui.dev/doc/subcriptions.md
code/tamagui.dev/features/site/purchase/NewAccountModal.tsx
code/tamagui.dev/features/site/purchase/StripePaymentModal.tsx

subscription: add billing information to checkout

---

code/ui/popover/src/Popover.tsx

Before: 
https://github.com/user-attachments/assets/ee8ea585-fe8e-474c-b3af-2bd5b84e8732
Afater: 
https://github.com/user-attachments/assets/f316f75d-f5a3-4329-b062-f75616cb73e5

fix(popover): close popover when click outside in native
