tamagui/tamagui

packages/tamagui/src/views/Label.tsx
This component has an action that checks if `htmlFor` is defined and do what it needs to do. However, the prop is required as of now, resulting in a type error if left undefined, and a warning if defined on mobile.
With this, the prop will be made optional. That will get rid of the type error, and still maintain the current behavior.
=> fix: make `htmlFor` optional on `Label` component. (fixes #65)

packages/site/data/docs/intro/configuration.mdx
Small fix on the Shorthands section of the docs.
=> fix(docs): @tamagui/shorthands package link

README.md
`./script/ci-prepare.sh` -> `./scripts/ci-prepare.sh`
=> fix: correct path to `ci-prepare.sh` in README

starters/next-expo-solito/apps/expo/package.json
Currently the tamagui-starter template will prevent expo from building due to the reason that no dev-client is present. This will confuse new users an I suppose this was also not intentional, otherwise the dev-client should be part of the `devDependencies`.
=> remove expo --dev-client and replace with -c

packages/tamagui/src/createTamagui.ts
Fixes issue where radius check yielded unexpected results
Example of issue:
```
createTamagui() invalid tokens.radius:
Expected subset of: $0, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $0.25, $0.5, $0.75, $1.5, $2.5, $3.5, $true, $4.5, $5.5, $6.5, $7.6, $8.5, $9.5
Received: $0, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $base, $true, $0.25, $0.5, $0.75, $1.5, $2.5, $3.5, $4.5, $5.5, $6.5, $7.6, $8.5, $9.5
Missing: $base
```
=> Fix radius token check

apps/site/data/docs/core/font-language.mdx
- Added a fix to the core font language page, correcting: "Simple create a `body` font, and a `body_french` font..." -> "Simply create a `body` font, and a `body_french` font..."
=> fix(site): fixed typo in font language docs

packages/list-item/src/ListItem.tsx
=> fix(list-item): Make sure icon after spacer does not use the full width if not content will end up being cropped

packages/core/src/createComponent.tsx
Delete font weight and style when the font family is being overridden due to a native font face.
This is due to a bug where font weights 700 or above will look for a bold variant that doesn't exist, and fall back on the platform font.
=> fix(core): delete weight/style when face applies

apps/site/data/docs/core/configuration.mdx
as discussed on discord, examples were showing font weight in a number rather than string -- the former which is turned into pixels and not picked up as a font.
i also changed the font `face` key to be a string. 
the first commit is for docs fix, the second commit changes font face to string in code if you want to keep that too.
=> fix config weight usage to be string

packages/create-tamagui-app/src/index.ts
Hi @natew - I've tested this on Windows and WSL (Linux) systems and it seem to solve the create app issues on Windows.
The main problem was coming from the "zx" library: https://github.com/google/zx/issues/551
It was creating commands which were not formatted correctly on Windows (specifically the commands related to git things), so they were failing. I've replaced the failing commands with `execSync()` instead, and all seems to work just as expected.
This PR should fix https://github.com/tamagui/tamagui/issues/312
=> Fix for create-tamagui-app for Windows

packages/static/src/extractor/loadTamagui.ts
Currently when you use pnpm you will get error:
```
Tamagui Webpack Loader Error:
next-app:dev:    Cannot find module '@my/ui'
```
This will fix it and will resolve @my/ui in workspace like for example next-app.
=> Should work with non hoisted to root of workspace dependencies (pnpm)

packages/helpers-tamagui/src/useCurrentColor.tsx
Currently when working with icons inside components and using the `getThemedIcon`, you are unable to pass color tokens from `tokens.color` which have not been declared explicitly in `createTheme({ ... })`.
This PR adds a fallback to the `useCurrentColor` hook to also look for the color in `tokens.color` when returning the current color.
=> fix: let useCurrentColor access token colors

starters/next-expo-solito/apps/next/pages/_app.tsx
The memoization here isn't necessary if we simply use the parent-child paradigm from React. Since `props` will have the same reference for `ThemeProvider`, updating the theme won't trigger any re-renders to its `props.children`.
More context here: https://kentcdodds.com/blog/optimize-react-re-renders
=> Simply `_app.tsx`

apps/site/data/docs/guides/next-js.mdx
Location: https://tamagui.dev/docs/guides/next-js (bottom of page)
The top code block uses `tsx` syntax highlighting, and the bottom code block is not. This PR adds `tsx` to the code block to present the code block with better formatting.
=> Add `tsx` for better syntax highlighting

.github/workflows/checks.yaml
I'm noticing PRs aren't running CI - the workflow is only hooked to "push" right now for branches local to this project. This should allow incoming PRs to also run the `checks.yaml` workflow.
=> build: run ci checks on pull requests

packages/focusable/src/focusableInputHOC.tsx, packages/focusable/src/registerFocusable.ts, packages/focusable/types/registerFocusable.d.ts
Alternative to #463. Fixes #462 
The same solution, but without an additional render.
* Update `focusableInputHOC` to unregister its component before attempting to register again
* Update `registerFocusable()` types + web implementation to match type shape of the native implementation
=> fix(focusable): unregister focusable Inputs before reregistering between renders

apps/site/data/docs/guides/design-systems.mdx
Simple fix to typo/grammar in design systems documentation.
=> Fix typo in design systems doc

packages/config-base/package.json, yarn.lock
While building a design kit - we imported `@tamagui/config-base` and built and it crashed with:
```
error: Error: Unable to resolve module @tamagui/react-native-media-driver from /Users/xxx/iOSProjects/xxx-app/node_modules/@tamagui/config-base/dist/cjs/media.js: @tamagui/react-native-media-driver could not be found within the project or in these directories:
node_modules
25 | });
26 | module.exports = __toCommonJS(media_exports);
> 27 | var import_react_native_media_driver = require("@tamagui/react-native-media-driver");
```
The project seems to use that import - https://github.com/tamagui/tamagui/blob/master/packages/config-base/src/media.ts#L1, but is missing it in the scoped `package.json`.
=> build: add missing react-native-media-driver dependency to config-base

packages/react-native-web-lite/package.json
Hi there, first of all, thanks for Tamagui, seems cool!
Just a quick PR to add the repo website and bugs link to [the `react-native-web-lite` npm package](https://www.npmjs.com/package/react-native-web-lite), which is currently not listed:
=> Add keys to react-native-web-lite package.json

apps/starter/apps/next/pages/_app.tsx, apps/starter/package.json, starters/next-expo-solito/apps/next/pages/_app.tsx, starters/next-expo-solito/package.json, starters/next-expo-solito/yarn.lock
Fixes #504
* Update the theme provider examples in the starter projects to call `startTransition` in their change handlers
* Here is the fix as applied to the bug reproduction repo: https://github.com/nderscore/tamagui-suspense-demo/tree/fix
* (the `site` app for the tamagui homepage already does this)
* Remove package resolution locking `@types/react` to an old 17.x version which predates the existence of `startTransition`
* I might be missing some prior knowledge as to why this was there in the first place, but I didn't notice any issues after removing it.
=> fix: update starters to use transition in next theme change handler

apps/site/data/docs/guides/design-systems.mdx
The previous URL is pointing to the archived repository.
=> Update starters URL in Design Systems guide

apps/site/data/docs/intro/compiler-install.mdx
I removed the babel part too since it was left halfway through. I imagine it has to do with `@tamagui/babel-plugin` but I'm not sure how you'd want that worded. Can push an update to this branch if you'd rather update that wording with something specific.
=> Fixed visual error in the installation page

packages/select/src/SelectImpl.tsx, packages/select/src/SelectScrollButton.tsx, packages/tamagui/src/setup.ts
Fixes #514
Fixes #519
* Restore native `cancelAnimationFrame` on web
* The `tamagui` package was adding a `try/catch` wrapper to `cancelAnimationFrame`, but this wrapper referenced itself (it shadows its own variable name) instead of the original `cancelAnimationFrame` method, causing an infinite loop whose error gets swallowed.
* This fixes the scroll buttons on the select as well as the never-ending `autoUpdate` after close
* Revert the change from cf2951a6
* Change was not necessary and doesn't seem to follow examples from floating-ui docs
* Pass `open` prop to `useFloating()` hook call in `SelectScrollButton`
* Not 100% sure this is necessary, but it felt right 😅
=> cancelAnimationFrame / floating-ui fixes

packages/button/src/Button.tsx
Related to GitHub issue #505 - Fixes broken link in comment.
Insignificant change, but I'd love to become familiar with the project.
=> fix(button) - typo - broken link in comment

packages/avatar/package.json, packages/button/package.json, packages/card/package.json, packages/cli/package.json, packages/compose-refs/package.json, packages/config-base/package.json, packages/core/package.json, packages/create-themes/package.json, packages/demos/package.json, packages/dialog/package.json, packages/helpers/package.json, packages/label/package.json, packages/normalize-css-color/package.json, packages/react-native-web-internals/package.json, packages/stacks/package.json, packages/static/types/extractor/extractMediaStyle.d.ts, packages/tamagui/package.json, packages/text/package.json, packages/theme-base/package.json, packages/timer/package.json, packages/use-controllable-state/package.json, packages/use-event/package.json, packages/use-force-update/package.json, packages/vite-plugin-reanimated/package.json, packages/vite-plugin/package.json
Currently, TypeScript fails to find declarations for `tamagui` (and many `@tamagui/*` packages) when using the `Node16` or `NodeNext` [module resolution strategy](https://www.typescriptlang.org/tsconfig#moduleResolution) (i.e. using ES modules). The reason for this is because all `package.json` files are missing the [`types` field within their `exports` maps](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing); this is only necessary when declarations aren't located next to the JavaScript files.
This PR:
- adds the missing field to all relevant `package.json` files
- adds a missing `StyleObject` import to `packages/static/types/extractor/extractMediaStyle.d.ts` (I'm not sure why the `build` action adds this only after making the …
=> [Issue] add missing "types" property to package.json "exports" maps

starters/next-expo-solito/apps/expo/app.json, starters/next-expo-solito/packages/app/provider/index.tsx, starters/next-expo-solito/packages/app/provider/navigation/index.tsx
Per [discussion](https://discord.com/channels/909986013848412191/1066854123095474186), starter only had light support, and if dark theme was forced, there were visual errors. Changes allow for automatic light/dark theme preference.
=> feat(native): preferred color scheme

packages/select/src/Select.tsx
wrong typescript extends interface for SelectItemProps
=> replace extends SelectItemProps from YStackProps to ListItemProps

apps/site/lib/mdx.ts
certified Windows moment
`DATA_PATH` has backslashes on Windows and slashes on Linux. Tried the fix and it works both on Windows and Linux.
Closes #625
=> fix: tamagui website issue on windows

packages/core/package.json
After the changes from 5b76e63c, I started seeing this error when trying to build the `@my/ui` package in my project:
> `src/MyComponent.tsx(3,14)`: error TS2742: The inferred type of 'MyComponent' cannot be named without a reference to `'../../node_modules/@tamagui/core/types/reactNativeTypes'`. This is likely not portable. A type annotation is necessary.
I wasn't able to reproduce this error using the starter repo with yarn 3.x, but it happens when using pnpm as the package manager.
---
The error is caused by a missing field in `exports` of the `@tamagui/core` package for this new entry point. 
This PR adds an entry for `./reactNativeTypes` with the correct paths, which fixes the error.
=> fix(core): add export path for reactNativeTypes

starters/next-expo-solito/README.md
Just an update on the docs regarding fixes for "Cannot use Import statement outside a module" when using libraries with native code and installing in the app directory.
=> withTM Update

apps/site/data/docs/core/configuration.mdx
The link leads to nowhere. I couldn't find any equivalent to [the old file that has been removed](https://github.com/tamagui/tamagui/blob/c3beeff4902388a420549abc608f1af7607658c9/packages/site/constants/themes.ts) in the site app.
=> docs: remove invalid link reference

apps/site/data/docs/intro/compiler-install.mdx
Per [the docs](https://github.com/babel/minify/tree/master/packages/babel-plugin-transform-inline-environment-variables), the `include` property takes an array of string values, not a string.
=> docs: Update compiler-install.mdx

apps/site/data/docs/guides/create-tamagui-app.mdx
Per the website docs one needs to run "yarn dev" which is not an available script. Replaced with "yarn web" and "yarn native" to avoid confusion.
=> docs: Mini-fix website starter guide

apps/site/data/docs/guides/expo.mdx
`react-native-reanimated` v3.0.0 has been released two days ago.
This version is not yet compatible with expo.
To be safe, I think we should use `expo install react-native-reanimated` to always install a compatible version of this library.
=> Docs: Install react-native-reanimated with expo cli

packages/switch/src/Switch.tsx
Between version 1.6.3 and version 1.7.0 the styles on Switch frames were commented out as if `unstyled` was always applied. Noticed that an `unstyled` prop also stopped being passed through.
| BEFORE | AFTER |
|---|---|
| <img width="766" alt="Screenshot from Switch page with switch frame not styled" src="https://user-images.githubusercontent.com/1854690/223749325-5a2842f6-2520-4284-be50-adcf422e456f.png">  | <img width="760" alt="Screenshot from Switch page with frame styles returned" src="https://user-images.githubusercontent.com/1854690/223749403-5f9caf81-bb54-4d53-80e9-28be9a23f2a2.png">  |
=> [fix] Style regression on Switch frame

packages/radio-group/src/RadioGroup.tsx
The default `button` tag on Web seems to be applying padding horizontally, which is breaking the `RadioGroup.Indicator`'s width. This fixes it.
=> fix: radio group incorrect sizing

packages/label/src/Label.tsx
The valid values for role are listed here:
https://reactnative.dev/docs/accessibility#role
label is not one of them, so it's producing an error in the console that appears to have started with expo 48.
This fixes #761 
Based on the description, heading seemed to be the most fitting.
=> Fix role value

apps/site/data/docs/components/list-item/1.0.0.mdx
i didn't like the formatting on the website so i fixed it
also had javascript errors (forgot an extra paren when copying it over)
=> Docs: fix formatting of list-item

.github/ISSUE_TEMPLATE/bug.yml
I've found creating issues/reproductions to be frequent yet difficult. I often don't do it because I don't want to pull the repo, rebase, make a new branch, etc. I think CodeSandbox simplifies this a lot. Just open a link and it's ready.
This PR also uses GitHub's new yml bug report templates, which look like this:
=> Bug Report Template

starters/next-expo-solito/README.md
there is no `yarn:prod` command, was it meant to be `yarn web:prod`?
=> chore(readme): fix starter yarn command

packages/get-size/src/index.ts
Fixes #559
Ensures that `keysOrdered` is tokenized (each `key` is prefixed with `"$"`).
Admittedly, this patches a side effect from a separate issue:
- `createVariables` _always_ removes the `"$"` prefix
- `tokensKeysOrdered` stores `size` and `space` tokens without the prefix
So, I'm not sure what the better approach is:
- the fix in this PR
- changing how `tokensKeysOrdered` [is set here](https://github.com/tamagui/tamagui/blob/master/packages/web/src/createVariables.ts#L51) by doing
```
tokensKeysOrdered.set(res, Object.keys(tokens).map((tokenWithoutPrefix) => `${tokenWithoutPrefix}`))
```
=> fix: [#559] ensure keysOrdered is tokenized

apps/site/data/docs/intro/benchmarks.mdx, packages/get-size/src/index.ts, packages/web/src/styled.tsx
extend automatically
BREAKING CHANGE: Technically this is a breaking change, though likely not one you'll run into any issues with. Nonetheless, we'll bump the minor version to make it a bit clearer and easier to downgrade.
=> feat(web): styled components now inherent the name from the parent they

apps/kitchen-sink/src/features/home/screen.tsx
Issue: The theme line item was not rounded by the Group wrapper.
The component wasn't passing down the props. I don't think if this was rounded before the Group changes (#735) either but I might be wrong.
=> fix: kitchen sink group not getting rounded

apps/site/data/docs/components/form/1.3.0.mdx
so that it's more clear and people less likely miss that (#771)
=> docs(form): add asChild to anatomy

packages/web/src/hooks/useAnimationDriver.tsx, packages/web/types/hooks/useAnimationDriver.d.ts
Users seem to have issues using this and are getting the `Must set animations in tamagui.config.ts at SheetImplementation2 ` .
Not sure why that is happening. Maybe context is not available on the first render and this is throwing? 
P.S. ignore the branch name as it's not a css driver issue, but a general animations one
=> fix(animations): add getAnimationDriver as fallback to useAnimationDriver

apps/site/data/blog/version-one.mdx, apps/site/data/docs/components/alert-dialog/1.0.0.mdx, apps/site/data/docs/components/card/1.0.0.mdx, apps/site/data/docs/components/dialog/1.0.0.mdx, apps/site/data/docs/components/form/1.3.0.mdx, apps/site/data/docs/components/headings/1.0.0.mdx, apps/site/data/docs/components/popover/1.0.0.mdx, apps/site/data/docs/components/select/1.0.0.mdx, apps/site/data/docs/components/sheet/1.0.0.mdx, apps/site/data/docs/components/sheet/1.9.18.mdx, apps/site/data/docs/components/stacks/1.0.0.mdx, apps/site/data/docs/components/toast/1.8.0.mdx, apps/site/data/docs/components/toast/1.9.1.mdx, apps/site/data/docs/components/tooltip/1.0.0.mdx, apps/site/data/docs/core/configuration.mdx, apps/site/data/docs/core/font-language.mdx, apps/site/data/docs/core/stack-and-text.mdx, apps/site/data/docs/core/styled.mdx, apps/site/data/docs/core/theme.mdx, apps/site/data/docs/core/variants.mdx, apps/site/data/docs/intro/introduction.mdx, apps/site/data/docs/intro/props.mdx, apps/site/data/docs/intro/themes.mdx
Figured would be easier for newbies. Will prevent version mismatch (which has happened before in the issues), when user has a version of `tamagui` and installs another version of a component and gets errors. 
Not sure about the `@tamagui/core` changes and if having `tamagui` as the default would be better for that case too but went ahead and changed those too.
=> fix(site): change all possible imports to `tamagui`

apps/site/data/docs/guides/expo.mdx
As `@tamagui/theme-base` is now deprecated.
=> expo guide: use themes instead of theme-base

packages/build/tamagui-build.js
I had the requirement to modify the declarationDir of esbuild. With this PR users can run
```
tamagui-build --declaration-root
```
To create declarations into the root folder. This is specific if library authors wants to export multiple folders of one package like:
```
import {} from 'tamagui-extras '
import {} from 'tamagui-extras/submodule'
```
=> Add option --declaration-root to tamagui-build

apps/site/data/docs/components/toast/1.13.0.mdx, next.md, packages/toast/src/ToastImperative.tsx, packages/toast/types/ToastImperative.d.ts
Figured users probably won't need to use the nativeToast property from the toast controller. They might get it in the auto-completion and find it a bit confusing but not super important.
=> fix(toast): remove native toast ref from public api + add docs

packages/sheet/src/Sheet.tsx
This prevents content from overflowing beyond the screen, especially if it is aligned to the bottom.
Fixes https://github.com/tamagui/tamagui/issues/940
Not 100% sure about this so I'd appreciate any feedback. Tested on macos chrome and ios safari and seems to be working well.
=> fix(sheet): Set sheet size as largest snap point.

packages/demos/src/ToastDemo.tsx, packages/toast/src/Toast.tsx, packages/toast/src/ToastImperative.tsx, packages/toast/src/ToastImpl.tsx, packages/toast/src/ToastProvider.tsx, packages/toast/src/ToastViewport.tsx, packages/toast/types/Toast.d.ts, packages/toast/types/ToastImperative.d.ts, packages/toast/types/ToastImpl.d.ts, packages/toast/types/ToastProvider.d.ts
fixes:
- events and multiple viewports where only the last viewport's events work
- variant types not being correctly inferred
- `additionalInfo` not being typed on `useToastState()`
- ability to pass `viewportName` to `useToastController()` 
also deprecates `additionalInfo` in favor of `customData`
=> fix(toast): bugs

packages/demos/src/LucideIconsDemo.tsx
I removed the `.slice(0,835)` from the code to correctly list newly added icons too.
=> fix(site): show all icons in demo by removing unnecessary slice

packages/next-plugin/src/withTamagui.ts
=> fix(next-plugin): allow `experimental` key in NextJS configs to be `unndefined`

packages/static/src/extractor/loadTamagui.ts
In our monorepo setup there was an error being thrown that others in the Discord seemed to have hit. It may have solved a lot of users cases with some recent fixes, but I think for monorepos or custom config locations it was still broken because `getDefaultTamaguiConfigPath` would get called and error out despite the config being ignored later.
This should fix it but ultimately to come up with a test environment for this small fix would be more effort then the issue itself. Let me know if I should come up with a test somewhere but ultimately this is a fairly small fix.
=> fix: Allow a config path to be passed without erroring

apps/site/data/docs/guides/create-tamagui-app.mdx
The previous doc link directs to an archived and outdated repo. This change simply updates that to the up-to-date repo link.
=> Updates outdated link in docs

packages/card/src/Card.tsx, packages/card/types/Card.d.ts
I don't know if it is an intentional thing, but I noticed that the card, due to the spread of the 'props' object, was losing the variant for the 'size', I also added `styleable` type instead of `extractable` which is deprecated
=> Fix Card Props

packages/tabs/src/Tabs.tsx
Would fix `<Tabs.Tab borderRadius={0} />`
=> fix(tabs): Tabs.Tab not applying user's borderRadius

packages/web/src/views/Text.tsx
Possibly related https://github.com/tamagui/tamagui/issues/1088#issuecomment-1529808972
=> fix(text): `Text` and `SizableText` not getting correct color on native

starters/next-expo-solito/apps/expo/app.json, starters/next-expo-solito/apps/expo/package.json, starters/next-expo-solito/packages/ui/src/CustomToast.tsx, starters/next-expo-solito/packages/ui/src/NativeToast.tsx, starters/next-expo-solito/yarn.lock
The current next-solito-starter fails in multiple places when creating an update with the expo eas service to view and share your tamagui project in the expo go app.
A couple of things I need to do to get the starter to work on expo go.
- remove expo-image: only works in development builds and sdk47. The starter doesn't use the package anywhere. (https://github.com/expo/expo/tree/main/packages/expo-image#installation)
- update eas with a runtime https://docs.expo.dev/eas-update/runtime-versions/#setting-runtimeversion
- Conditionally add toasts if not in expo go. Expo Go doesn't support native modules. IMO not having toasts in expo go outweigh the cost of not being able to use the starter in expo go.
- updated the app.json my app to `yourprojectname` to be a little bit more on the nose to …
=> (fix) EAS update / build / expo go compatibility in solito starter

starters/next-expo-solito/apps/expo/package.json
expo documentation uses `npx expo` commands. 
https://docs.expo.dev/get-started/expo-go/
currently a developer could use a legacy version, and possibly cause issues building the app.
=> starter: update starter commands

packages/create-tamagui/src/index.ts
Small QoL improvement [inspired by](https://github.com/vercel/next.js/blob/canary/packages/create-next-app/helpers/git.ts#L33) create-next-app, this change adds an initial commit when initializing the starter so the user doesn't end up with a bunch of untracked files when opening the code.
Tested with running `yarn test` in the `create-tamagui` package.
=> feat(create-tamagui): add initial commit when using git

apps/site/data/docs/core/configuration.mdx
Resolve typo in [configuration](https://tamagui.dev/docs/core/configuration) docs
=> fix(docs): resolve typo

starters/next-expo-solito/apps/expo/app.json
https://stackoverflow.com/questions/71888858/no-launchable-updates-found-in-database-expo-go
Need to omit the runtime for the expo go app to load on `yarn native`
repro:
- `npm create tamagui`
- `yarn`
- `yarn native`
- choose ios
default starter should load
=> (fix)starter: expo on initial load

starters/next-expo-solito/.gitignore, starters/simple-web/.gitignore
when yarn installing packages, project tracked node modules in git, now we ignore them
https://stackoverflow.com/questions/29820791/git-ignore-node-modules-folder-everywhere
=> (fix)starters: add node_modules to ignore

starters/simple-web/src/tamagui.config.ts
=> overrided TamaguiCustomConfig interface for typed access to properties

packages/slider/src/Slider.tsx
Currently, it's not possible to manually define dimension styles on `Slider.Thumb`:
```tsx
<Slider.Thumb
width="$4"  // this does
height="$2" // nothing! 😭 
/>
```
This is because inside the wrapper around that component, the `size` prop is always inserted _after_ any custom user-defined props.
This PR moves the spreading of user-defined props to be after any predefined style props, enabling consumers to define or override `width`/`height`/`minWidth`/`minHeight` styles without using the `size` prop.
=> fix(slider): allow Thumb size styles to be overridden

packages/group/src/Group.tsx
fixes the bug where first/last element wouldn't get the correct border radius cause of conditionally hidden (null) nodes
=> fix(group): stop counting null children as group items

packages/web/src/helpers/insertStyleRule.tsx
Some old browsers assign null instead of throwing a SecurityError on the accessing cssRules.
=> fix: check for cssRules nullability

apps/site/data/docs/core/styled.mdx
Follow up to a discord discussion that pointed out a typo in the docs.
Also, I don't understand what this means, and thus can't rephrase it either, could you clarify it a bit?
> *Note that theme will automatically now happen above this HigherOrderStyledText so it's available if you use useTheme.*
=> docs(styled): clarify comments on `stylable`

starters/next-expo-solito/.vscode/settings.json, starters/next-expo-solito/apps/next/.vscode/settings.json
I _think_ it's more appropriate to have that directory in the root of the monorepo because usually people open the entire repo when developing and that setting and prompt only works if VSCode finds `.vscode` in the root.
=> chore(starter): move .vscode dir to the monorepo root

packages/static/src/extractor/bundleConfig.ts, packages/static/src/extractor/getTamaguiConfigPathFromOptionsConfig.ts, packages/static/src/extractor/loadTamagui.ts, packages/static/src/require.ts, packages/static/types/extractor/getTamaguiConfigPathFromOptionsConfig.d.ts
Updates logic to check if the path passed into the extractor is an absolute path, if it is, uses that directly instead of prepending the current working directory.
I wasn't able to get kitchen-sink or site running locally so if someone that is able to run those could please double check I didn't break this I would appreciate it 🙇
=> Allow absolute path to tamagui config

packages/button/src/Button.tsx, packages/button/types/Button.d.ts, packages/web/src/constants/accessibilityDirectMap.native.tsx, packages/web/src/constants/accessibilityDirectMap.tsx, packages/web/src/helpers/getSplitStyles.tsx, packages/web/types/constants/accessibilityDirectMap.d.ts, packages/web/types/constants/accessibilityDirectMap.native.d.ts
as most of the core Tamagui components are using `aria-*` and `role` for accessibility, it means that accessibility is mostly broken in native, in this PR it's mapping those web-specific aria and role props to its React Native counterpart.
=> accessibility improvement: native support web `aria-*` and `role`

packages/label/src/Label.tsx
Got rid of height in order to fix the vertical alignment issue mentioned in #1298 
The fix assumes tokens between font and size match, but it was assumed prior to this anyways.
Closes #1298
=> fix(label): vertical alignment inconsistency between web and native

apps/site/data/docs/components/checkbox/1.3.0.mdx
=> docs: add missing `indeterminate` type to `onCheckedChange` callback

README.md
added the following badges:
- npm downloads
- commits per month
- discord users online (for this to work you need to enable it on the server: https://vimeo.com/364220040)
can be previewed [here](https://github.com/la55u/tamagui/tree/master#readme)
=> chore: add readme badges

README.md, package.json
The user needs to create a development build to run kitchen-sink (custom metro bundler). This step isn't included in the Readme. Added a new script to create a development build and then included these in the docs.
=> Added a section in readme about dev build for kitchen-sink.

packages/create-tamagui/src/helpers/cloneStarter.ts
no reason to cd three directories up on prod
Potentially fixes https://github.com/tamagui/unistack/issues/12
=> fix(create-tamagui): put chdir under test flag

packages/popover/src/Popover.tsx
Had to add a `Stack` wrapper since passing the prop directly to the animating element wasn't working
Fixes #1396 "Popover allows pressing even when closed "
=> fix(popover): disable pointer events when animating out

apps/site/components/DocsCodeBlock.tsx
Copy button in hero component does not work. Content of code block is gathered by query selector. However, this query runs only on the first mount but code block is not rendered in hero at that time becuase it is a collapsible block. We should get the content whenever code block is visible.
=> fix copy code in hero

apps/site/data/docs/core/use-theme.mdx
Additional backticks in mdx causing formatting issues on docs site at https://tamagui.dev/docs/core/use-theme. 
**Before:** 
**After:**
=> docs(site): fix mdx typo

packages/web/src/createComponent.tsx
This is a fix for a bug I encountered when using a styled context which has only boolean props, with `false` as their default value.
The code inside `createComponent` which determines whether a prop is set was using `||` to short-circuit. Depending on the order they're defined in, this swallows `false` values unexpectedly, because `false || undefined` resolves to `undefined`.
When a context prop is `false`, it is being excluded from the context value. When all the context props are `false`, the context provider is never rendered at all.
A reproduction of this bug can be found [here](https://github.com/nderscore/tamagui-styled-context-null)
* Replace the short-circuiting OR (`||`) in `createComponent` with nullish-coalescing operators (`??`)
* Merge parent styled context value into …
=> fix(core): make styled context handle boolean props

packages/demos/src/LucideIconsDemo.tsx
=> fix(demos): use `includes` on lucide icon demo for better search

packages/scroll-view/src/ScrollView.tsx, packages/scroll-view/types/ScrollView.d.ts
For now I've only picked `scrollTo`. We probably only want to pick the ones that are shared between web and native. 
Usage:
```tsx
import { ScrollView } from 'tamagui'
const ref = useRef<ScrollView>(null)
ref.current?.scrollTo() // is typed
```
Input would be appreciated @natew.
Fixes #1486
=> fix: export ScrollView type to use on `useRef`

packages/select/src/Select.tsx
selected item lose its selected state after being unmounted ( select closed ) and reset it back to initial value
`isSelected = React.useState(initialValue === value)`
trigger that `emitter` again once Select open
=> Fix selectItemIndicator not behaving correctly

starters/next-expo-solito/README.md
Related: https://github.com/tamagui/unistack/issues/71 & https://discord.com/channels/909986013848412191/974145843919716412/1107249160442351616
=> docs(next-expo-starter): bad path on vercel section of README.md

apps/site/lib/codeExamples.tsx
This PR fixes wrong style output in compiler > about docs ["How Tamagui Helps"](https://tamagui.dev/docs/intro/why-a-compiler#how-tamagui-helps), where the given example in "media" tab shows a prop-based (shrink prop) style with transform scale property. Currently the output shows a wrong background style inside a gtSm media query, with this modification it will show the corresponding transform property inside a sm media query, with a tamagui-generated class name (generated using simple-web starter).
=> docs: fix wrong transform style in compiler media example

packages/web/src/helpers/getSplitStyles.tsx
Fixes #1491 Font weight for Android are not using the correct font family
=> fix(web): font weight not working correctly on android

packages/web/reset.css
Not sure if this was a problem for anyone else, but I found that when my content overflows the viewport vertically, it causes horizontal scrollbars due to the body not accounting for the space of the vertical scrollbars.
Adds dynamic width calculation to prevent horizontal scrollbar when vertical scrollbars are present.
=> fix(web): vertical scrollbar causes horizontal

packages/label/src/Label.tsx
According to WAI-ARIA 4, Document conformance requirements for use of ARIA attributes in HTML
https://www.w3.org/TR/html-aria/#docconformance
label role is prohibited and must not have a role, so the role should be removed.
=> fix(Label): Label is not supposed to have a role

packages/portal/src/Portal.native.tsx
This would allow components that use Portal to be used inside iOS native modals. Popover is still misplaced inside native modals, but that would be a separate issue.
Closes #944 - Missing RootTag warning when using Popover 'modal' property.
=> fix(portal): fallback to `PortalItem` if no `RootTagContext` is available

packages/web/src/helpers/insertStyleRule.tsx
It would produce `jc-row` instead of `_jc-row`, resulting in selectors not being found and styles not being applied properly
Instead of `_jc-row` being inserted on the element, it would insert `_jc-undefined`
It appears to be a race condition, where these styles are attempted initially and fail. But if they were to be attempted a bit later, they should succeed. However, this does not occur
Let me know if I can assist with getting this over the line 🙏 Thanks!
=> Off-by-1 error with getting identifier from style rule

packages/demos/src/SheetDemo.tsx, packages/sheet/src/SheetImplementationCustom.tsx, packages/sheet/src/createSheet.tsx, packages/sheet/src/types.tsx, packages/sheet/src/useSheetOffscreenSize.tsx, packages/sheet/src/useSheetProviderProps.tsx, packages/sheet/types/Sheet.d.ts, packages/sheet/types/SheetContext.d.ts, packages/sheet/types/SheetImplementationCustom.d.ts, packages/sheet/types/createSheet.d.ts, packages/sheet/types/types.d.ts, packages/sheet/types/useSheet.d.ts, packages/sheet/types/useSheetOffscreenSize.d.ts, packages/sheet/types/useSheetProviderProps.d.ts
Adds a new prop to the `Sheet` component called `snapPointsMode`, which changes the behavior of the `snapPoints` prop. 
The possible values for this prop are:
- `percent` - the default, treat snap points as numeric percentages
- `constant` - treat snap points as constant pixel dimensions
- `fit` - auto-fit to the content's inherent height
- `mixed` - a mixture of multiple types (`numbers` = pixels, `"${number}%"` = percentages, `fit` = fit)
If a snap point value is greater than the height of the parent container, it will be constrained to the height of the parent container.
When in non `percent` modes, an extra View is rendered to measure the height of the parent container in order to get the correct `screenHeight` without being able to do percentage math on the sheet's height.
When an …
=> feat(sheet): add option for constant snapPoint sizes in pixels

apps/site/data/docs/components/sheet/1.59.0.mdx, packages/demos/src/SheetDemo.tsx, packages/sheet/src/SheetImplementationCustom.tsx, packages/sheet/src/createSheet.tsx, packages/sheet/src/useSheetOffscreenSize.tsx
Improves the implementation of the Sheet's "fit" snap points mode. 
After these changes I was able to remove all the fit-mode-specific changes to the SheetDemo (key prop, extra styles). I think I got it right this time 🤞 
- Moved fit mode's frame size measurement layout handler back to the AnimatedView where it probably belongs
- Set `forcedContentHeight` constraint to `undefined` when in fit mode - previously this was being constrained to the initial frame size before measurement (`0`)
- Conditionally toggle the frame to `flex: 0` when in fit mode
- Update offscreen calculation to always return `0` when in fit mode.
- Without this, the `data-sheet-offscreen-pad` element changes the height of the frame when the sheet is partially off screen, causing nasty layout measurement loops
- Fixed …
=> fix(sheet): better implementation of 'fit' snap points mode

packages/react-native-use-pressable/src/index.ts, packages/react-native-use-pressable/types/index.d.ts
`usePressEvents` in `@tamagui/react-native-use-pressable` should be fixed, otherwise `Pressable` won't work in `react-native-web-lite`.
In `react-native-web-lite`, the calling code is `usePressEvents(hostRef, config)`. This part is derived from `react-native-web`.
This fix is to keep this calling interface the same.
=> fix: usePressEvents's first argument should be hostRef

packages/demos/src/SwitchDemo.tsx, packages/demos/types/SwitchDemo.d.ts, packages/switch/src/Switch.tsx, packages/switch/src/createSwitch.tsx
This fixes a visual bug with the switch component. When it is initially checked (either with `defaultChecked` or the `checked` prop) the starting position of the thumb is out of the boundaries of the switch frame. 
A demonstration of this issue can be seen on the Tamagui docs site on demos with an animation switch:
https://github.com/tamagui/tamagui/assets/2250252/9dec3a4e-607f-4576-b5a0-cbaf54319913
* Set initial position of the switch's thumb without needing any measurements
- Update tamagui's `SwitchFrame` component to use `YStack` instead of `XStack`, so that the thumb can position itself using flex alignment
- Update Switch Thumb component to alter its starting position based on the initial value of `checked`/`defaultChecked`. When initially checked, the thumb aligns itself to …
=> fix(switch): fix starting position of thumb when switch is initially checked

packages/sheet/src/SheetImplementationCustom.tsx
Fixes measurement of the sheet height on mobile web by removing an old workaround that added extra height on mobile browsers.
I tested all modes after making this change with mobile Safari's dynamic bottom bar in different positions and everything seemed to still be working.
https://github.com/tamagui/tamagui/assets/2250252/5b38c53d-f391-4611-80e8-257744e38feb
=> fix(sheet): sheet height measurement on mobile web

packages/constants/src/index.android.ts, packages/constants/src/index.ios.ts, packages/constants/src/index.native.ts, packages/constants/types/index.android.d.ts, packages/constants/types/index.ios.d.ts, packages/constants/types/index.native.d.ts
Updates the type definitions of all code-splitting paths to match the un-suffixed web version.
This should handle cases where someone has [**compilerOptions.moduleSuffixes**](https://www.typescriptlang.org/tsconfig#moduleSuffixes) set to something like `[".ios", ".native", ""]` in their typescript configuration.
=> fix(constants): use matching types on all code splitting paths

packages/cli/src/add.ts
~Not tested yet~ Tested. Works as expected. 
TODO: do the same for `create-tamagu`.
=> fix(cli): fallback to ssh if https failed on `add`

packages/sheet/src/SheetImplementationCustom.tsx
Gives `"fit"` snap points in mixed mode the same maximum height constraint as when using `snapPointsMode="fit"`
=> fix(sheet): add missing height constraint to fit points in mixed mode

packages/toast/src/createNativeToast.native.tsx
I noticed that my native toasts were never ending, while my web toasts were working as expected. Turns out, that if we input 2000ms, we end up with a 2,000,000 second toast on native!
This issue stems from us multiplying instead of dividing the `duration` option to match Burnt's spec (which says duration should be in seconds).
=> Fix native toast timing to match burnt specification + tamagui docs

packages/switch/src/createSwitch.tsx
This PR implements an alternative to using border width in the calculations for moving the Switch component's Thumb.
Instead of measuring the frame directly, an additional view is rendered inside the frame.
=> fix(switch): avoid needing border width for distance calculation

packages/switch/src/index.ts, packages/switch/types/index.d.ts
Adds a missing export for `SwitchContext` on the `@tamagui/switch` package. 
Previously this was exported from another file.
=> fix(switch): export SwitchContext for headless consumers

packages/loader/src/TamaguiPlugin.ts, packages/loader/types/TamaguiPlugin.d.ts, packages/next-plugin/src/withTamagui.ts, packages/next-plugin/types/withTamagui.d.ts
close https://github.com/tamagui/tamagui/issues/1755
It fixes type definitions to avoid that using next app router make jsx build failed.
=> Make next-plugin types accept loader-options

apps/site/data/docs/guides/expo.mdx
this does not spark joy 😭
I added a real link, so that devs can open another extra tab
=> docs(expo): add real link to expo.dev typescript setup

starters/next-expo-solito/apps/expo/package.json, starters/next-expo-solito/apps/next/package.json, starters/next-expo-solito/package.json, starters/next-expo-solito/packages/app/package.json, starters/next-expo-solito/yarn.lock
this is step 1, update packages
next PR's will update expo to 49
tested both web and native iOS
specifically, addressing this warning with the PR
=> run npx expo install react-native@0.71.13 react-native-safe-area-context@4.5.0 typescript@^4.9.4

packages/web/src/types.tsx, packages/web/types/types.d.ts
This fixes a regression in the types of `styleable()` introduced in [1.74.20](https://github.com/tamagui/tamagui/releases/tag/v1.74.20) by these commits:
- 3db30bf7
- fa19f604
Ever since this version, the inner function of `styleable` has an inferred type of `FunctionComponent<any>`
This PR restores default prop types for the inner function.
---
I tested this out on my local project and all of our `styleable` wrappers seem to be working as expected. We have at least once instance of a double-wrapped `styleable` (`Foo.styleable(...).styleable(...)`) and it seems fine too.
=> fix(core): infer correct prop types for inner function of styleable

starters/next-expo-solito/README.md, starters/next-expo-solito/package.json
Issue this addresses:
The PR requested by nate [here in discord](https://discord.com/channels/909986013848412191/1116381883748585563/1151169168679370813). 
Issue summarized:
Strictly following the current readme instructions for the next-expo-solito starter repo results in a failed deployment with the error shown below. 
What this PR does:
- This PR updates the package.json vercel:install script to use `set version stable`. 
- This results in a failure with yarn 4.0.0 (current stable) because of [this yarn update](https://github.com/yarnpkg/berry/issues/5817), so it also updates the build script to include the `--all` flag. 
- It also updates the readme instructions for the starter repo. 
Together these changes result in a successful github push auto-deploy on vercel.
```
> Detected …
```
=> Next-Expo-Solito starter: fix vercel deployment issue

apps/site/data/docs/components/tabs/1.7.0.mdx
Fix Tabs usage example throwing error, Text strings must be rendered within a <Text> component.
=> Correct tab usage example

packages/tooltip/src/Tooltip.tsx
Tried buidling the project.
Fails on tooltip
Prop change gets the tooltip to build.
I deleted the project and tried from a clean install to confirm it wasn't a local change.
=> fix tooltip prop, build failing

CONTRIBUTING.md
native documentation is incorrect. `yarn ios` creates local development build
=> update contributing docs to create dev build

starters/simple-web/src/animations.ts, starters/simple-web/src/fonts.ts, starters/simple-web/src/media.ts, starters/simple-web/src/tamagui.config.ts
As a newbie,
I can quickly understand how to create a simple custom theming,
So that I can enjoy tamagui.
---
I created a new project and it was a bit "complex" to understand where to put my declarations because the actual `tamagui.config.ts` mixes external files and "inline" declarations.
**before**
```
.
├── Root.tsx
├── index.tsx
├── tamagui.config.ts <----- mix config with declarations
├── themes.ts
└── tokens.ts
0 directories, 5 files
```
**after**
```
.
├── Root.tsx
├── animations.ts
├── fonts.ts
├── index.tsx
├── media.ts
├── tamagui.config.ts  <------- one config file to rule them all
├── themes.ts
└── tokens.ts
0 directories, 8 files
```
=> split simple-web starter config into separate files

apps/site/data/docs/intro/compiler-install.mdx
This is a small PR fixing 404 links in docs
=> fix: 404 links in docs

.github/ISSUE_TEMPLATE/bug.yml
fix bug template.
Sorry about the back-and-fourth. Bug template doesn't preview in a branch on `tamagui/tamagui`, I shouldn't have assumed it was working with out actually seeing it render.
Repo:
- Created a fork
- made changes in PR
- double checked bug template is working as expected.
=> bug.yaml fix

packages/slider/src/Slider.tsx
We can update the value when clicking the track,
but we need always call `onSlideStart` at any time
=> Fix the Slider.onSlideStart is not called when clicking the thumb

packages/sheet/src/SheetScrollView.tsx
This assures that we do not skip the "scrollBridge" values processing
when passing this prop into a <Sheet.ScrollView /> overriding it here
Useful when using this ScrollView with lists such as [FlashList](https://github.com/Shopify/flash-list), i.e.
```
renderScrollComponent={Sheet.ScrollView}
```
=> Process the "onScroll" prop in Sheet.ScrollView

packages/skeleton/package.json, yarn.lock
yarn install rn linear gradient for native skeleton. Not 100% if we'll use this since we're using tamagui/linear-gradient
=> yarn install rn  linear gradient

packages/tamagui/src/views/Input.tsx, packages/tamagui/types/views/Input.d.ts
The `disabled={value}` prop is translated to `editable={!value}` in `useInputProps`, and causes "editable is deprecated. Use readOnly." warning. so use `readOnly` instead of `editable`.
=> fix: use readOnly prop instead of editable for Input to avoid a warning

packages/generate-themes/src/generate-themes.ts, packages/themes/src/generated-new.ts, packages/themes/src/generated-v2.ts
This has better typing and won't break when `noImplicitAny` is on
=> fix(generate-themes): better types for the generated theme

packages/dialog/src/Dialog.tsx
In my app, if I try to do something like:
```ts
styled(Dialog.Title, { })
```
I get errors that text cannot render within a React Native `View`. Something is going wrong with the composition.
Changing Dialog to extend via `styleable` instead of a `React.forwardRef` appears to fix this issue.
As always, happy to adapt this PR or my codebase 🙏 Thanks!
=> Use styleable for Dialog Title & Description

starters/simple-web/src/themes.ts
palettes have light and dark keys in the wrong order. They need to be swapped.
=> Fix: theme palettes keys swapped in correct order

apps/site/data/docs/core/stack-and-text.mdx
View component has defaultProps that injects flexDirection: 'column'. Hence this content block is not applicable. Check the code below:
```
export const View = createComponent<StackProps, View, StackPropsBase>({
acceptsClassName: true,
defaultProps: {stackDefaultStyles},
validStyles,
})
```
=> docs: removed content that is not applicable

README.md
I was going to make a PR for a feature, but then I realized that the current writing guide link is incorrect. 
Add `blob/master` to that link and it will work well now.
=> fix(docs): writing guide link

apps/site/data/docs/intro/themes.mdx
I've found this message within the Theme docs:
> we recommend doing this because it avoids a category of confusing type errors
I'm not 100% sure which type of type errors this refers to, but judging by the steps performed below, it seems like the new-ish [`satisfies`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html#the-satisfies-operator) operator might simplify it a lot.
=> [Docs] use `satisfies` for defining theme collection

packages/font-size/src/getFontSize.ts
This PR fixes a regression in behavior that was caused by this commit:
https://github.com/tamagui/tamagui/commit/0154e14b6ae1cb6cc3776d274db6bf97083907b4
After upgrading to a version that includes this change, I started receiving numerous console warnings because my fonts do not have a `$4` token:
```
No font size found $4 undefined in size tokens 
```
- Only replace `$true` with `$4` when there is no `$true` token defined for the font
=> fix(font-size): avoid replacing $true with $4 when it is a defined token

packages/select/src/Select.tsx, packages/select/types/Select.d.ts
Fix for this TypeScript error when inferring types from the `Select` component.
```
error TS4023: Exported variable 'MySelect' has or is using name 'SelectValueExtraProps' from external module "/path/to/node_modules/@tamagui/select/types/Select" but cannot be named.
```
=> fix(select): export SelectValueExtraProps interface

packages/config/src/animations.reanimated.ts
This resolves a problem with using Reanimated animations - the compiler is unable to resolve the `/types` import correctly.
=> Import package, not types

packages/popper/src/Popper.tsx
I'm sure there's a reason for this offset by 1, perhaps if it's on a corner? Perhaps it's to account for a border, but even with the border it's still noticeable
At the moment, with a transparent Tooltip, you can see the visible overlap between the two.
Reproducable example:
```ts
<Tooltip placement='top'>
<Tooltip.Trigger>
<Text>Trigger</Text>
</Tooltip.Trigger>
<Tooltip.Content
animation='fast'
enterStyle={{ x: 0, y: 5, opacity: 0, scale: 0.9 }}
exitStyle={{ x: 0, y: 5, opacity: 0, scale: 0.9 }}
scale={1}
x={0}
y={0}
opacity={1}
borderColor='rgba(100, 100, 100, 0.4)'
backgroundColor='rgba(100, 100, 100, 0.4)'
style={{ backdropFilter: 'blur(8px)' }}
>
<Tooltip.Arrow
borderColor='rgba(100, 100, 100, 0.4)'
backgroundColor='rgba(100, 100, 100, 0.4)'
style={{ backdropFilter: 'blur(8px)' }} …
```
=> Don't offset Popper arrow by 1 when on bottom

packages/build/tamagui-build.js
This allows opting into excluding certain files from being built with `tamagui-build` via regex. my main use case for this is it was picking up my inline `.stories` files from storybook and building those.
It also opts out of picking up the babel config files as that proved to be the root cause of some build issues with `mjs` that I was dealing with. This can be parameterized too if needed but I figure it should always be `false`?
=> feat: add exclude option to tamagui-build and opt out of picking up babel config

packages/popover/src/Popover.tsx
This PR would change the render mechanism of `<Popover/>`, return null will be moved one level up meaning that the portal `DIV/VIEW` will not be rendered if not visible. 
This aims to cleanup the created DOM elements and hopefully also solves some issues with trap focus if too many popovers would be rendered on a page.
=> Move return null of Popover.Content not visible one level up

apps/site/data/docs/guides/theme-builder.mdx
docs seem to reference second arg, but it doesn't exist.
=> fix docs, theme func arg

packages/select/src/Select.tsx
Currently, when using a Select with native enabled  (`<Select native />`), the `id` is not getting passed to the native `<select />` component.
This PR's goal is to fix the native web select so that it can be properly identified by `id`
I can't migrate to Tamagui from NativeBase because I can't select options in my playwright tests
```typescript
await beeperPage.getByLabel('Make').selectOption('Ford');
``` 
- Spin up the main site locally and verified that the `id` shows on the "native" example
| Before | After |
|--------|-------|
|   ![broken](https://github.com/tamagui/tamagui/assets/6440455/5bcf0ea7-3519-4b55-bd8a-071fe0b8607a)     |  ![fixed](https://github.com/tamagui/tamagui/assets/6440455/d9a707e4-9050-4d83-8fc3-c48cb90d9fd5)   |
=> fix(select): Select `id` not getting passed to the native web select

apps/site/data/docs/components/toast/1.9.1.mdx
Native toasts will error out when running your app with Expo Go. This is mentioned [here](https://github.com/nandorojo/burnt?tab=readme-ov-file#expo).
=> Add note about native toasts and Expo Go

apps/site/data/docs/guides/expo.mdx
Currently if you copy/paste the code that's in the installation instructions, you'll get a Typescript error because of the import name mismatch. This PR fixes that.
=> Updated import name

apps/site/components/BentoPageFrame.tsx, apps/site/pages/bento/index.tsx
Improved footer spatial placement on Bento homepage.
-  Simplified  `BentoPageFrame` component by removing the `simpler` prop, which was not used, and adjusted the footer padding dimensions.
-  Added a separator on top of the footer.
=> style: fix footer

apps/site/components/SeasonToggleButton.tsx
=> fix season button overflow

packages/dialog/src/Dialog.tsx
I do not feel like it is supposed to warn a message, feel free to change the content of the warning if necessary
=> chore(dialog): remove cryptic console warn

packages/switch/src/createSwitch.tsx
fix #2413
- because unstyled was always the last prop that made it to always override user-provided props
=> fix(checkbox): ignoring user provided props

packages/sheet/src/SheetImplementationCustom.tsx, packages/sheet/src/types.tsx, packages/sheet/types/Sheet.d.ts, packages/sheet/types/SheetImplementationCustom.d.ts, packages/sheet/types/createSheet.d.ts, packages/sheet/types/types.d.ts
will fix this issue [discord](https://discord.com/channels/909986013848412191/1208891297457504286/1219306834788225166) by letting the user to add `FullWindowOverlay` from `react-native-screens` as a wrapper to render modal on top of ios modal when `presentation: 'modal'` in `react-navigation` Stack.screen
```tsx
<Sheet
containerComponent={useMemo(
() => (props) => (
<FullWindowOverlay>
<View flex={1} pointerEvents="box-none">
{props.children}
</View>
</FullWindowOverlay>
),
[]
)}
```
=> feat(sheet): support custom container

packages/popover/src/Popover.tsx
Allow to close popover imperatively. It's useful when you don't want to take over the control over `open` value and want to close it manually at some point.
=> feat(popover): imperative close

packages/adapt/src/Adapt.tsx
I find it very useful to have the ability to distinguish between iOS and Android separately.
Technically it can be achieved by `isIos` and `isAndroid` but JSX declarative way is way much more readable and consistent.
=> feat(adapt): ios/android disctinction

apps/site/data/docs/components/unspaced/1.0.0.mdx
This PR fixes some minor typos in the Unspaced documentation.
=> docs: fix typos in Unspaced 1.0.0.mdx

packages/web/src/createComponent.tsx
`forceStyle` need to pass down to the underlying `staticConfig.Component` 
for example following case will not work
```jsx
const Button = styled(_Button, {
name: 'Button',
tag: 'button',
backgroundColor: 'red',
hoverStyle: {
backgroundColor: 'blue',
},
pressStyle: {
backgroundColor: 'yellow',
},
})
export const Sandbox = () => (
<Button forceStyle="press" />
)
```
fix #2396
=> fix(core): forceStyle not passing down

apps/site/pages/ui/[...slug].tsx
fix the issue where turning tint on/off crashed the demos on the site
=> fix(site): tint switch crash issue

packages/floating/package.json
This moves react-dom to peerDependencies for better support of upcoming React 19
=> Move react-dom of floating to peerDependencies

CONTRIBUTING.md
[https://github.com/tamagui/tamagui/apps/site/WRITING-GUIDE.md](https://github.com/tamagui/tamagui/apps/site/WRITING-GUIDE.md)
<br><br>
[https://github.com/tamagui/tamagui/blob/master/apps/site/WRITING-GUIDE.md](https://github.com/tamagui/tamagui/blob/master/apps/site/WRITING-GUIDE.md)
=> Broken link/contributing.md: Update writing guide link

apps/site/data/docs/guides/expo.mdx
fix: type issue at `app/_layout.tsx`
issue:
Type 'ColorSchemeName' is not assignable to type 'string | undefined'.
Type 'null' is not assignable to type 'string | undefined'.ts(2322)
```tsx showMore fileName="app/_layout.tsx"
import '../tamagui-web.css'
import { DarkTheme, DefaultTheme, ThemeProvider } from '@react-navigation/native'
import { Stack } from 'expo-router'
import { useColorScheme } from 'react-native'
import { TamaguiProvider } from 'tamagui'
import { tamaguiConfig } from '../tamagui.config'
export default function RootLayout() {
const colorScheme = useColorScheme()
return (
// add this
<TamaguiProvider config={tamaguiConfig} defaultTheme={colorScheme!}>
<ThemeProvider value={colorScheme === 'dark' ? DarkTheme : DefaultTheme}>
<Stack>
<Stack.Screen name="(tabs)" options={{ …
```
=> chore: Update TamaguiProvider defaultTheme prop in expo.mdx

apps/x/app/(site)/takeout.tsx, apps/x/features/site/home/HomeTypography.tsx, apps/x/features/takeout/TakeoutLogo.tsx
**site**
-diff HeroTypography to HomeTypography
- site removed use of passThrough prop from Delay component
-diff Community to HomeCommunity
- SocialLinksRow (same, no changes)
- Card (same, no changes)
**general vxs port issues found:**
theme change does not change text font color
regression notes:
I am seeing a regressions of component reviewed from weekend changes. ‘code preview’ and ‘resize breakpoint’ not working correctly.
**takeout**
- TakeoutGallery
- TakeoutImage (takeout image has not code changes. Yet not showing. when debugging the src has the correct path, its a problem with props miss behaving, some are missing like objectFit. Looks like its related to Image component.
- Takeout index
- TakeoutPage
- CodeInline (no changes)
- points (no changes)
- TakeoutCard2Frame diff
- …
=> vxs takeout diff fixes

CONTRIBUTING.md
Fix possible textual errors in CONTRIBUTING.md for clarity and accuracy.
* “... you may see some errors around "studio" as you run build - this is fine, we encrypt some of the non-open-source projects in the repo. The errors block anything.” - should be “The errors does not block anything”?
* “yarn watch:build”: should be “yarn watch”? As I did not find any `"watch:build"` occurrences in the code base.
=> docs: fix textual errors in CONTRIBUTING.md for clarity and accuracy

code/packages/babel-plugin-fully-specified/package.json, code/packages/babel-plugin-fully-specified/src/__tests__/__snapshots__/index.test.ts.snap, code/packages/babel-plugin-fully-specified/src/__tests__/fixtures/.gitignore, code/packages/babel-plugin-fully-specified/src/__tests__/fixtures/force-extension/bar.js, code/packages/babel-plugin-fully-specified/src/__tests__/fixtures/force-extension/foo.js, code/packages/babel-plugin-fully-specified/src/__tests__/fixtures/multiple-extensions-exists/modules/module.cjs, code/packages/babel-plugin-fully-specified/src/__tests__/fixtures/multiple-extensions-exists/modules/module.js, code/packages/babel-plugin-fully-specified/src/__tests__/fixtures/multiple-extensions-exists/modules/module.mjs, code/packages/babel-plugin-fully-specified/src/__tests__/fixtures/multiple-extensions-exists/test.mjs, code/packages/babel-plugin-fully-specified/src/__tests__/fixtures/sample-project-1/modules/cjs-module.cjs, code/packages/babel-plugin-fully-specified/src/__tests__/fixtures/sample-project-1/modules/module.mjs, code/packages/babel-plugin-fully-specified/src/__tests__/fixtures/sample-project-1/node_modules/@my-org/my-pkg/lib/exampleFunction.js, code/packages/babel-plugin-fully-specified/src/__tests__/fixtures/sample-project-1/node_modules/@my-org/my-pkg/lib/index.js, code/packages/babel-plugin-fully-specified/src/__tests__/fixtures/sample-project-1/node_modules/@my-org/my-pkg/package.json, code/packages/babel-plugin-fully-specified/src/__tests__/fixtures/sample-project-1/node_modules/README.md, code/packages/babel-plugin-fully-specified/src/__tests__/fixtures/sample-project-1/test.mjs, code/packages/babel-plugin-fully-specified/src/__tests__/index.test.ts, code/packages/babel-plugin-fully-specified/src/index.ts, code/packages/babel-plugin-fully-specified/types/index.d.ts, code/packages/build/tamagui-build.js, yarn.lock
#2761 (specifically, [this commit](https://github.com/tamagui/tamagui/pull/2761/commits/ba6d76540dc67a6f9ac1ba7f06a88631ada947b4)) breaks the build because:
* `@tamagui/build` is using `babel-plugin-fully-specified` to transform `.js` into `.mjs`, with `ensureFileExists` set to `true`.
* We expect those transformed `.mjs` to also import from transformed `.mjs` files.
* But during the transformation, the file being imported might not be transformed yet, and that `.mjs` file will not exist. With `ensureFileExists`, we can only find the `.js` file at that time, so the `.js` file is used instead, which is not what we want and will break things because that `.js` file isn't a transformed one.
To prevent this, a `forceExtension` option is added for forcing the usage of a specific extension for …
=> feat(babel-plugin-fully-specified): implement and use forceExtension

code/ui/switch/src/createSwitch.tsx
This is the same fix as for Checkbox. 
Clicking on a Label HTMLFor results in an error:
No input found for id $id
This registers the ID so the Switch can be controlled by Press on the Label.
=> Register Switch's ID so Label can update it

.vscode/settings.json, code/packages/build/tamagui-build.js
Save the source maps for .mjs files (output by applying babel-plugin-fully-specified), which are currently not saved.
Tested with vxrn and tamagui.
=> feat(build): output source map for .mjs files

code/core/web/src/createComponent.tsx
in `code/core/web/src/helpers/getSplitStyles.tsx:170`, we have:
```ts
const rulesToInsert: RulesToInsert =
process.env.TAMAGUI_TARGET === 'native' ? (undefined as any) : {}
```
So, on native, `const keys = Object.keys(splitStyles.rulesToInsert)` will cause error `Cannot convert undefined value to object`.
I think this might be a fix for that.
=> fix(core): `rulesToInsert` can be undefined on native

code/core/web/src/createComponent.tsx
Fixes: #2773 
Before refactor:
https://github.com/tamagui/tamagui/blob/148e67ac5976110e9a405318a1db5265878ec69c/packages/web/src/createComponent.tsx#L287-L296
We now missing the !staticConfig.acceptsClassName.
This pr attempts to restore that condition
Used this component to verify that works on sandbox:
```tsx
function MyComponent({ style, onMouseEnter, onMouseLeave }) {
console.log(" => style", style, onMouseEnter, onMouseLeave);
return (
<div
style={{ width: 20, height: 20, ...style }}
onMouseEnter={onMouseEnter}
onMouseLeave={onMouseLeave}
></div>
);
}
const MyStyledComponent = styled(MyComponent, {
name: "MyStyledComponent",
backgroundColor: "red",
hoverStyle: {
backgroundColor: "blue",
},
});
export default function StyledHTMLTags() {
return (<MyStyledComponent debug={"verbose"} …
```
=> fix(web): avoid classes if acceptsClassName is not set

.yarn/patches/h3-npm-1.11.1-e4c2aa03b9.patch, code/takeout/package.json, code/tamagui.dev/package.json, package.json, yarn.lock
Use [`yarn patch`](https://yarnpkg.com/features/patching) to patch h3 since the patches in takeout will not be applied in this yarn workspaces monorepo.
=> patch h3 for vxrn

code/core/animations-moti/src/createAnimations.tsx
This PR added possibility to specify and apply animations for `font` related styles with Moti animations driver.
=> feat(animations-moti): added font related styles to animateOnlyKeys

code/tamagui.dev/data/docs/core/configuration.mdx
defaultProps in config, seems to be broken and deprecated in config code example, above so document it here as well
https://codesandbox.io/p/sandbox/old-bash-fyt776?file=%2Fsrc%2FApp.tsx%3A40%2C4
=> doc: configuration.mdx/defaultProps - add deprecated note

code/starters/expo-router/package.json
- Updated @tamagui/metro-plugin from version 1.108.2 to 1.108.3 in package.json
Implementation reason: This update ensures compatibility with the latest features and bug fixes provided by the @tamagui/metro-plugin, improving the overall stability and performance of the project.
=> chore(expo-router): Update @tamagui/metro-plugin version

code/tamagui.dev/data/docs/components/sheet/1.59.0.mdx
would like to close #2836 
Let me tell you this, the bento portion of this monorepo is very difficult to deal with as an external contributor. Both for this and for the kitchen-sink I had to manually go and remove every references to bento within the code to be able to start the projects. I tried to find info on how to effectively deal with it while contributing but didn't find anything useful.
Also the contributing documentation is sparse, sometimes vague and currently very little maintained.
If there is a true will into enabling external contributors, there is some work to do (more info down below).
Is it ok to manually edit the last version of the sheet's mdx file or should I generate a new one containing the latest version of tamagui with some command?
_Examples:_ 
1. I tried to …
=> docs: add unmountChildrenWhenHidden in props table

code/tamagui.dev/data/docs/guides/create-tamagui-app.mdx
When I try to access `npm create tamagui@latest` *Check out the source of the templates* , get a 404 error occurred. I believe the new template link should be this one.
=> fix: external link error

.github/workflows/create-tamagui-expo-router.yml
- Added a new GitHub Actions workflow file `.github/workflows/create-tamagui-expo-router.yml`
- The workflow triggers on push to the main branch, pull requests, and manual dispatch
- It sets up Node.js, creates a Tamagui project using the Expo Router template, and starts the Expo project
- Includes steps to check if the Metro bundler is ready and handle potential startup failures
Implementation reason: This workflow automates the testing of the Tamagui Expo Router setup, ensuring that the project can be created and started successfully, which helps maintain the reliability and stability of the project.
=> feat(workflow): Add GitHub Actions workflow for testing Tamagui Expo Router setup

package.json
For developers with [Corepack](https://nodejs.org/docs/latest-v20.x/api/corepack.html) enabled, the `"packageManager"` field in `package.json` will be used by Corepack to automatically determine which version of the package manager should be used for the current project.
https://nodejs.org/docs/latest-v20.x/api/packages.html#packagemanager
When developers with Corepack enabled run the `yarn` command, the `"packageManager"` field in the root `package.json` will be automatically added with the following message shown:
```
! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e.
! For more details about …
```
=> add "packageManager" field in package.json for corepack

code/tamagui.dev/data/docs/components/select/1.40.0.mdx
The docs mention using `SheetContents` or `Select.SheetContents` to insert content into the Adapt, but it should be `Adapt.Contents` or `Select.Adapt.Contents`
=> Fix typo in Select docs

.vscode/settings.json
Not to be overwritten by user’s language-specific settings.
=> chore(vscode): ensure that biome will be used

code/tamagui.dev/data/docs/guides/design-systems.mdx
Actually the links on design system documentation page are pointing to a invalid address on repo.
How to reproduce:
- Access https://tamagui.dev/docs/guides/design-systems
- Click on "create-tamagui is itself a well structured monorepo." or "More complete, the tamagui package itself." line.
=> fix: design system doc links

code/ui/input/src/types.ts
I had issue setting the color of the Input component exported from `@tamagui/input`.
The typing for the color prop comes from `DetailedInputProps['style']` which is the basic HTML color type. It's not completely true since it accepts custom theme values coming from tamagui. 
What I've done is simply exclude the color property from `DetailedInputProps['style']` to use the one coming from `TextProps` from `@tamagui/web`.
=> fix: allow custom color type for input

code/packages/bento-get/src/app/AuthGuard.tsx, code/packages/bento-get/src/cli-components/SearchBar.tsx, code/packages/bento-get/src/commands/index.tsx, code/packages/bento-get/src/hooks/useInstallComponent.tsx, code/packages/bento-get/src/screens/CodeAuthScreen.tsx, code/packages/bento-get/types/app/AuthGuard.d.ts
- Updated the token change listener in CodeAuthScreen to properly unsubscribe when the component unmounts
- Wrapped the listener in a useEffect hook to ensure proper lifecycle management
- move useEffect back to React.useEffect for `npx`
Implementation reason: The fix addresses a potential memory leak by ensuring that the event listener is properly removed when the component is unmounted. This change improves the overall performance and stability of the application.
Users using `npx bento-get` instead of `yarn dlx bento-get` were getting import errors in production build.
=> fix(bento-get): Correct event listener cleanup for token changes and npx

code/packages/bento-get/package.json, yarn.lock
- Changed React dependency from fixed version to support both React 18 and 19
Implementation reason: This change allows for greater flexibility in React version compatibility, enabling the package to work with both current and future React releases.
- File changed: code/packages/bento-get/package.json
=> chore(deps): unpin React dependency in bento-get package

code/ui/list-item/src/ListItem.tsx
The Text components inside the ListItem were previously set to cursor: default, causing an issue where even if the ListItem had cursor: pointer, the cursor would still display as default. This behavior prevented the intended cursor style from being inherited from the parent.
To resolve this, I’ve changed cursor: default to cursor: inherit in ListItemText, allowing the Text components to inherit the cursor style from their parent elements. Additionally, I’ve set cursor: default as the default style for ListItemFrame to maintain consistency where needed.
| AS-IS | TO-BE |
|----------|----------|
| <img width="816" alt="스크린샷 2024-09-07 오전 2 57 31" src="https://github.com/user-attachments/assets/4ac93449-9392-4bf7-bdde-a13f0188d523"> | <img width="1091" alt="스크린샷 2024-09-07 …
=> fix(ui): change cursor default to inherit in ListItemText

code/packages/build/.gitignore, code/packages/build/__tests__/fixtures/simple-package/index.d.ts, code/packages/build/__tests__/fixtures/simple-package/index.d.ts.map, code/packages/build/__tests__/fixtures/simple-package/package.json, code/packages/build/__tests__/fixtures/simple-package/src/index.ts, code/packages/build/__tests__/fixtures/simple-package/tsconfig.json, code/packages/build/__tests__/fixtures/watch-package/index.d.ts, code/packages/build/__tests__/fixtures/watch-package/index.d.ts.map, code/packages/build/__tests__/fixtures/watch-package/package.json, code/packages/build/__tests__/fixtures/watch-package/src/watch.ts, code/packages/build/__tests__/fixtures/watch-package/tsconfig.json, code/packages/build/__tests__/fixtures/watch-package/watch.d.ts, code/packages/build/__tests__/fixtures/watch-package/watch.d.ts.map, code/packages/build/__tests__/integration.test.ts, code/packages/build/package.json, code/packages/build/tamagui-build.js, code/starters/expo-router/yarn.lock, yarn.lock
- Replace call to `npx tsc` with typescript compiler directly
- Aim for consistent types output on build, regardless of environment, npm/node version
- Tested per package builds, and master build on this repo.
`yarn test`
- Basic build: Verifies correct output of CJS, ESM, and type declaration files.
- Bundle: Checks bundling functionality.
- Skip MJS: Confirms --skip-mjs option works as expected.
- Ignore base URL: Tests --ignore-base-url option.
- Watch mode: Ensures rebuilding on file changes when using --watch.
- Platform-specific output: Validates correct generation of web and native-specific code.
- Minification: Verifies output is minified when MINIFY=true is set.
Each test checks for file existence, content correctness, and specific functionality of the build process. The suite …
=> feat(build): migrate tamagui-build from `npx tsc` to `typescript` compiler API

code/ui/sheet/src/SheetImplementationCustom.tsx
In https://github.com/tamagui/tamagui/pull/2873, I changed `Dimensions.get('window').height` to `Dimensions.get('screen').height` to fix the issue of incorrect sheet maxContentSize on Android. Since the screen height doesn’t change when the keyboard appears, it is no longer necessary to listen for keyboard changes here. Additionally, as the sheet component re-renders when the keyboard changes—including all sheet components in the page stack—removing `useKeyboardVisible` improves performance, especially in complex forms with many sheet components.
=> perf(sheet): avoid unnecessary rendering on keyboard chanage

CONTRIBUTING.md, code/ooo/data/docs/common-issues.mdx, code/ooo/data/docs/routing-modes.mdx, code/packages/lucide-icons/src/icons/github.tsx, code/tamagui.dev/app/(site)/takeout.tsx, code/tamagui.dev/data/blog/version-one-release-candidate.mdx, code/tamagui.dev/data/blog/version-one.mdx, code/tamagui.dev/features/site/header/Header.tsx, code/tamagui.dev/features/site/purchase/helpers.tsx, code/tamagui.dev/features/takeout/TakeoutPolicy.tsx, code/tamagui.dev/features/user/claim-product.ts
There are a number of places where GitHub is incorrectly capitalized as Github. This corrects those errors.
=> Fix capitalization of GitHub

code/tamagui.dev/data/docs/components/headings/1.0.0.mdx
The Headings documentation says to use `@tamagui/headings` but the components are in the package `@tamagui/text`.
See https://tamagui.dev/ui/headings?subpath=headings
This PR corrects to the text package
=> docs(headings): correct install banner package to text

code/ui/accordion/src/Accordion.tsx
As reported on Discord (https://discord.com/channels/909986013848412191/909986013848412194/1242282248754040883) and in our own experience, tapping the Accordion rapidly causes the content to be rendered, but the height to not expand correctly.
An inspection of the code seemed to show that the laid out height of the children was being overridden by the dynamic 'open' height, causing the state to be lost after toggling.
This fixes it to make the height state only contain the laid out height, leaving the animation 'open' height as a purely derived value.
=> Fix the accordion losing height

code/tamagui.dev/data/docs/guides/theme-builder.mdx
Fix theme-builder guide by including missing createTheme hard-coded mapper function params. Also remove mentions of masks, a concept which was previously removed from the guide for the sake of simplicity.
=> Update theme-builder guide createTheme params

code/ooo/data/docs/exports-withLayoutContext.mdx
fixed a typo, so good to have native bottom tabs supported!
=> docs: fix typo in `exports-withLayoutContext.mdx`

code/tamagui.dev/data/docs/components/list-item/1.0.0.mdx
ListItemProps is unused, ListItemTitle and ListItemSubtitle are required.
=> docs: fix imports for ListItem customization example

code/ui/tamagui/package.json
Tamagui entry lacks the description in React Native Directory:
* https://reactnative.directory/?search=tamagui
For monorepo packages we relay on [`description` in `package.json`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#description-1), with no fallback to GitHub repository description.
Not sure if this is the correct/ideal description of the package, just copied over what was the highlight sentence in the main repo.
In the process, I have also spotted that `repository` entry points to the incorrect directory inside monorepo.
=> [tamagui] Updates for `package.json`

code/tamagui.dev/features/docs/InlineTabs.tsx
Replace `useLocalSearchParams` with `useParams` in `InlineTabs` component for improved routing
=> 🐛 fix: Document

code/tamagui.dev/components/RovingTabs.tsx, code/tamagui.dev/features/docs/DocsCodeBlock.tsx
| Before | After|
----|---- 
| <img width="400" alt="スクリーンショット 2025-01-14 12 09 41" src="https://github.com/user-attachments/assets/e9d75f67-c497-4353-bbd7-0a56cb315e59" />  | <img width="400" alt="スクリーンショット 2025-01-14 12 09 54" src="https://github.com/user-attachments/assets/f090b783-2884-491f-8ab2-1fb0f063059a" /> |
- Fixed an issue where bash commands were overflowing outside their container
- Unified scrolling behavior between bash commands and regular code blocks
- Improved code structure in RovingTabs component
=> Fix code block horizontal scrolling behavior

code/tamagui.dev/app/(site)/theme+spa.tsx
=> 🐛 fix: wrap ThemePage return in YStack for improved layout structure

code/ui/components-test/Input.web.test.tsx, code/ui/input/src/Input.tsx
Fixes #2926
- Added proper type conversion from React Native's keyboardType to HTML input type for the web
- Implemented `secureTextEntry` and `keyboardType` support for native
The component tests (`*.web.test.tsx`) in the codebase are currently not running. This should be addressed in a separate PR to ensure all web-specific tests are properly executed.
=> fix: Input keyboard type and secure text entry support

code/core/web/src/types.tsx, code/core/web/types/types.d.ts
Previously mentioned on #3089, the `GetAltThemeNames<S>` type does not properly capture intermediate theme names.
Given theme definitions for `light`, `light_Button`, and `light_secondary_Button`, it should be possible to pass `secondary` as a theme.
This PR adds support for those theme keys.
=> fix: allow intermediate theme keys on `Theme` type definition

code/ui/tooltip/src/Tooltip.native.tsx, code/ui/tooltip/types/Tooltip.native.d.ts
On RN, doing this
```tsx
import { closeOpenTooltips } from 'tamagui'
closeOpenTooltips()
```
will cause a weird error, due to `closeOpenTooltips` not being exported in `.native` and the bundler will try to import `closeOpenTooltips` from the wrong package since in `tamagui` `index.native.js` there's a lot of `export * from "..."`.
=> fix: importing tooltip stuff should behave as expect on RN

code/core/web/package.json, yarn.lock
If you don't have react-native installed in your project you'll loose autocomplete because @tamagui/web imports props from it. This PR adds react-native as a dev dependency to @tamagui/web so both  @tamagui/web and @tamagui/core packages can be used without people installing react-native - e.g. targeting only web platform.
=> fix props autocomplete when react-native is not installed

code/tamagui.dev/app/(site)/account.tsx, code/tamagui.dev/app/(site)/login.tsx
Fix: https://discord.com/channels/909986013848412191/1178185454386941982/1335990827809243227
I removed the `read:org` scope from GitHub OAuth login to minimize required permissions.
I initially tried to remove permissions from existing users as well, but it seems that Supabase Dashboard's Authentication doesn't store scope information, so we couldn't dynamically change scopes on our side.
However, this is not a big issue because:
- New users won't be asked for this permission when logging in
- For existing users, when they disconnect and reconnect their GitHub account, the scope will be automatically minimized
=> Remove `read:org scope` from GitHub OAuth login

code/tamagui.dev/features/site/purchase/NewPurchaseModal.tsx
part of #3182
This PR adds dynamic pricing calculation for the purchase modal:
- Base price: $200/year
- Chat support: $100/month ($1,200/year)
- Support tiers: $1,000/month per tier (up to 5 tiers)
=> Add dynamic pricing for chat support and support tiers

code/tamagui.dev/supabase/plan-migrations/01_cancel_existing_subscriptions.sql, code/tamagui.dev/supabase/plan-migrations/02_insert_product_tamagui_start.sql, code/tamagui.dev/supabase/plan-migrations/03_insert_product_tamagui_chat.sql, code/tamagui.dev/supabase/plan-migrations/04_insert_product_tamagui_support.sql, code/tamagui.dev/supabase/plan-migrations/05_insert_price_tamagui_start.sql, code/tamagui.dev/supabase/plan-migrations/06_insert_price_tamagui_chat.sql, code/tamagui.dev/supabase/plan-migrations/07_insert_price_tamagui_support.sql
This PR cancels the old Takeout and Bento subscriptions and sets up new product and pricing records for our updated revenue model as part of #3182 
Changes include:
- Updating the subscriptions table to cancel active and trial subscriptions.
- Adding new product records in the products table for:
- Tamagui Start (unified plan including Takeout, Bento, Theme AI, Chat AI, Discord #support, and Early access).
- Tamagui Chat (private Discord room access for teams).
- Tamagui Support (prioritized development support at $1000 per tier per month).
- Adding new price records in the prices table for:
- Tamagui Start at $200 per year.
- Tamagui Chat at $100 per month.
- Tamagui Support at $1000 per tier per month.
These SQL files have not been tested yet. Currently, we do not have a dedicated …
=> Migrate to New Tamagui Start and Support/Chat Plans

code/packages/next-theme/src/NextThemeProvider.tsx
Trying to upgrade Tamagui from ^1.120.0 to ^1.123.17 recently, I got some TS type-checking errors in Jonline's Tamagui FE: https://github.com/JonLatane/jonline/tree/main/frontends/tamagui
This should fix them, and should be pretty safe.
=> Fix theme type-checking errors

code/ui/input/src/Input.tsx
Allow the use of `time` or any other input related types. Currently there is a map and I am unsure why this is not allowing all input type variants.
=> Allow type prop on new Input.tsx

code/tamagui.dev/app/api/bento/zip-download+api.ts, code/tamagui.dev/features/auth/supabaseAdmin.ts, code/tamagui.dev/features/bento/hasBentoAccess.ts, code/tamagui.dev/features/site/purchase/NewAccountModal.tsx
- Add `getBentoBundleZip` function to fetch ZIP from Supabase storage
- Create new `/api/bento/zip-download` endpoint for authenticated downloads
- Update Account Modal's Bento download button to use the new endpoint
=> Implement Bento bundle download in Account Modal

code/tamagui.dev/scripts/migrate-subscription.mjs
This script handles the migration of subscriptions from the old Bento/Takeout products to the new Tamagui Pro plan. The migration process includes:
1. Finding all active subscriptions for old products (Bento/Takeout)
2. Creating new subscriptions under the Tamagui Pro plan
3. Setting up a trial period until the end of their current billing period
4. Canceling old subscriptions
5. Maintaining detailed migration logs
=> Subscription Migration Script

code/ui/slider/src/Slider.tsx
When you tap on the slider track in the vertical slider, it doesn't move properly. (Android, IOS)
https://github.com/user-attachments/assets/bfb5f178-1d0a-44f8-adbd-9cdd4e687eeb
When you tap on the slider track, it moves correctly.  
https://github.com/user-attachments/assets/c2928cfa-9636-4caf-bc25-aef1d5cc91e5
=> fix(slider): prevent slider-active-track to capture event instead of slider-track. so it gives different locationY

code/tamagui.dev/app/api/create-subscription+api.ts, code/tamagui.dev/app/api/upgrade-subscription+api.ts, code/tamagui.dev/features/site/purchase/NewPurchaseModal.tsx, code/tamagui.dev/features/site/purchase/StripePaymentModal.tsx, code/tamagui.dev/supabase/plan-migrations/06_insert_price_tamagui_chat.sql
1. Fixed the one-time purchase flow ($400) which was incorrectly handled
2. Added Chat Support as a new monthly service option ($200/month), being handled through upgrade-subscription API
=> Refine Purchase Flow

code/core/themes/types/generated-v4-tamagui.d.ts, code/kitchen-sink/package.json, code/kitchen-sink/src/App.tsx, code/ui/focusable/src/focusableInputHOC.tsx, code/ui/focusable/types/focusableInputHOC.d.ts, code/ui/tamagui/src/views/Input.tsx, code/ui/tamagui/types/views/Input.d.ts
Reference: https://x.com/mimameid/status/1895225010601795954
I investigated the slow focus performance of Tamagui's [Input](https://tamagui.dev/ui/inputs) component, which showed a 32.5x slower focus time compared to native input (6.5ms vs 0.2ms) as shown below:
Through profiling, I discovered that the main bottleneck was in the focus process itself, not in ref access or element casting (both took 0.00ms). The delay was primarily caused by:
1. Multiple style recalculations during focus
2. Unnecessary re-renders of props and theme values
I implemented several optimizations by memoizing the input props, optimizing placeholder text color calculations, ref callbacks, and event handlers.
These changes should reduce the focus delay by minimizing unnecessary calculations and re-renders during …
=> perf(Input): optimize focus perf on Input

code/tamagui.dev/app/api/stripe/webhook+api.ts, code/tamagui.dev/scripts/migrate-one-time-payments.mjs
When users purchase a Pro plan with disableAutoRenew=true, the system creates a one-time payment invoice instead of a subscription. This causes two problems:
1. The webhook handler doesn't process invoice.paid events (only handles checkout.session.completed)
2. As a result, one-time payment users don't get their subscription records in the database
1. Add webhook handler for one-time payments
- Added invoice.paid event handler in webhook+api.ts
- The handler creates subscription records for one-time payment invoices
- Sets subscription status to active with a one-year validity period
2. Add migration script
- Created scripts/migrate-one-time-payments.mjs to:
- Find all paid invoices for Pro plan one-time payments
- Create missing subscription records for existing customers
- Add …
=> Fix one-time payment subscription handling and add migration script

code/core/web/src/helpers/propMapper.ts
Closes #3177
if you add the following context and variant to any component.
```
export const context = createStyledContext({
color: '',
})
const StyledView = styled(View, {
context,
variants: {
color: {
'...color': () => {
return {}
},
},
}
})
```
it will give you this error 
TypeError: Cannot use 'in' operator to search for '' in undefined. 
This issue happens because config V3 and V4 tokens don't include color, and this snippet code tries to check the color
```
const { tokensParsed } = conf
for (const { name, spreadName } of tokenCats) {
if (spreadName in variant && value in tokensParsed[name]) {
return variant[spreadName]
}
}
```
so `tokensParsed[name]` is undefined  and  `value in tokensParsed[name]` crash the app.
I removed the color from the tokenCats array, which will no longer …
=> fix(core): deleted color from tokenCats array because it is not existed in config v3 and v4.

code/core/core/src/getBaseViews.native.ts, code/ui/portal/src/Portal.native.tsx
In the incoming React Native 0.79 release, we've converted a number of internal modules to `export` syntax — affecting usages with `require()`. This PR attempts to update these imports ahead of time, to work with both versions.
💡 Secondary note: In a future release, we are intending to omit each of these deep-imported modules from the public API of React Native. There will be a consultation period on opening up new APIs via the root `'react-native'` exports. Some of the uses in this library may need `@ts-ignores` in future.
**Needs testing**. CI should pass for integration with current RN versions.
=> Update react-native deep imports for 0.79 compatibility

code/tamagui.dev/data/docs/components/new-inputs/1.0.0.mdx
=> docs: migrate legacy `space` for `gap` on Inputs

code/tamagui.dev/app/_middleware.tsx, code/tamagui.dev/public/llms.txt
This PR adds two features to make Tamagui docs more accessible to LLMs:
1. Adds a middleware that serves raw markdown content when accessing URLs with .md extension (e.g., /ui/button.md)
2. Adds llms.txt that provides an index of all available documentation with markdown-formatted links
Reference: https://x.com/bunjavascript/status/1900062594578178538
=> Add LLM-friendly markdown endpoints and documentation index

code/core/core/src/getBaseViews.native.ts
Will close [3347](https://github.com/tamagui/tamagui/issues/3347)
- fix issue where TextAncestor is not properly imported
It looks like an error is coming from this potentially now:
```
console.js:614 Warning: Rendering <Context.Consumer.Consumer> is not supported and will be removed in a future major release. Did you mean to render <Context.Consumer> instead?
```
This may need more investigation
=> fix: import of TextAncestorModule

code/ui/slider/src/Slider.tsx, code/ui/slider/src/SliderImpl.tsx, code/ui/slider/src/constants.tsx, code/ui/slider/src/index.ts, code/ui/slider/src/types.ts, code/ui/slider/types/Slider.d.ts, code/ui/slider/types/constants.d.ts, code/ui/slider/types/index.d.ts, code/ui/slider/types/types.d.ts
- Use new createStyledContext instead of old createScopeContext
- Make the slider easier to customize, especially the slider Thumb sizes
=> chore(Slider): use new styledContext and make it easier to customize

code/core/core-test/getSplitStyles.native.test.tsx, code/core/core-test/getSplitStyles.web.test.tsx, code/core/web/src/helpers/getSplitStyles.tsx, code/core/web/src/helpers/mergeProps.ts
- Fix the `mergeProps` to keep the props order correctly:
- Example: 
```
const StyledButton = styled(Button, {
pressStyle: {
bg: '$blue10',
},
variants: {
disabled: {
true: {
bg: '$gray10',
},
},
variant: {
default: {
pressStyle: {
bg: 'red',
scale: 1.05,
},
},
},
},
})
// case 1
<StyledButton variant='default' pressStyle={{ bg: 'orange' }} ... />
// case 2
<StyledButton pressStyle={{ bg: 'orange' )) variant='default' ... />
```
- Before: 
```
output props:  
case 1: {pressStyle: {bg: 'orange'}, variant: 'default'}
case 2: {pressStyle: {bg: 'orange'}, variant: 'default'}
```
- After: 
```
output props:  
case 1: {variant: 'default', {pressStyle: {bg: 'orange'}}
case 2: {pressStyle: {bg: 'orange'}, variant: 'default'}
```
=> fix(variant): variant props priority

code/core/web/src/createComponent.tsx, code/core/web/src/hooks/useComponentState.ts
- Remove early return on disabled state to allow animations to work
- Allow state updates for animations when component is disabled
- Skip context group subscription for disabled components to prevent interactive states
- Maintain existing behavior for non-disabled components
https://github.com/user-attachments/assets/54d243ce-9468-4ce7-bd53-5023af464b55
=> fix(animations): allow enterStyle animations to work on disabled component

code/tamagui.dev/app/api/bento/zip-download+api.ts, code/tamagui.dev/features/user/helpers.ts
- Updated zip-download+api.ts to allow users in whitelistBentoUsernames (by GitHub username or email) to download the Bento zip, bypassing the subscription check.
- Updated getUserAccessInfo in helpers.ts to use the same direct whitelist logic for Bento access.
=> fix: allow direct Bento whitelist access for zip download

.github/workflows/build-ios-kitchensink-app.yml, .github/workflows/test-native-ios.yml, code/kitchen-sink/app.json, code/kitchen-sink/package.json, code/kitchen-sink/testing-utils/getWebDriverConfig.ts, code/kitchen-sink/testing-utils/global-setup.ts, code/kitchen-sink/tests/sample.test.ios.tsx, code/kitchen-sink/vitest.config.ios.ts, package.json, yarn.lock
The convention, I feel, is that running `test` will run all `test:*`.
But for iOS native tests, there are some reasons not to run them with all other tests, but to run them separately:
* They cannot run on non-macOS machines.
* On CI, macOS runners are much more expensive.
```sh
cd code/kitchen-sink
yarn vitest --config ./vitest.config.ios.ts --run
```
While on CI, we build the native kitchen-sink app and store it in the cache, then download the app before running native tests, and pass the path to the built test app via the `IOS_TEST_CONTAINER_PATH_DEV` and `IOS_TEST_CONTAINER_PATH_PROD` environment variables. When running locally, normally the `IOS_TEST_CONTAINER_PATH_DEV` and `IOS_TEST_CONTAINER_PATH_PROD` environment variables won't be set, and the test setup script will automatically …
=> test: Setup iOS native kitchensink test

code/starters/expo-router/app/_layout.tsx
Replaced react-native StatusBar with expo-status-bar to ensure the status bar adapts correctly to light/dark mode.
Fixes theming issue in tamagui expo-router starter.
=> fix(starters): use expo-status-bar to sync status bar color with system theme

code/tamagui.dev/app/api/logout+api.tsx, code/tamagui.dev/features/site/purchase/NewAccountModal.tsx
fix(site): improve logout flow and redirect handling
- Replace direct location.href navigation with fetch API call
- Change logout endpoint to use POST method for better security
- Fix redirect issues in both development and production
This fixes the issue where:
- Production: Redirected to blank page at /api/logout
- Development: Changed host to 0.0.0.0 after logout
=> fix(site): redirect handling after logout

code/tamagui.dev/features/site/header/Header.tsx
Super tiny typo. (Mainly just wanted an excuse to go spelunking through the codebase 🤓)
This is buried in the hamburger menu.
I considered pulling this out into a variable or switching on the types, but felt that was potentially overkill and a wider blast radius for something so small.
=> Add missing 'r' in "Compiler"

code/core/constants/src/constants.native.ts
Error
```
"IS_REACT_19" is not exported by "../../node_modules/@tamagui/constants/dist/esm/index.native.js", imported by "../../node_modules/@tamagui/web/dist/esm/helpers/wrapStyleTags.native.js"
```
=> fix: add missing IS_REACT_19 for native

code/tamagui.dev/data/docs/intro/themes.mdx
The `extractable` docs says that it is deprecated... is my understanding of how to use the `styleable` replacement correct?
=> docs(themes): update extractable usage to styleable

code/ui/alert-dialog/src/AlertDialog.tsx
The root cause of the AlertDialog breaking on native after commit `8393831998c3667c57be56e5d6ebf4e0520aa440`
What happened:
1. In the refactoring, we removed all displayName assignments from AlertDialog components
2. The AlertDialog components (Title, Description, Action, Cancel) were using React.forwardRef, making them regular React components
3. `isTamaguiElement(child)` returned false for these components
4. The logic fell back to `child.type['displayName']`, which was undefined (since we removed them)
5. Result: Native AlertDialog couldn't identify any components → broken functionality
The Fix:
Converted all AlertDialog components to use the styled() + .styleable() pattern (like Dialog components)
https://github.com/user-attachments/assets/62cf9ffa-4a21-4d30-b8cf-cfcb16dab740
=> refactor(alert-dialog): convert components to use styled API

code/core/web/src/views/FontLanguage.native.tsx
Found a bug in the `FontLanguage` component on native:
When using `FontLanguage` inside the `TamaguiProvider` the `animationProvider` and all other props from the `ComponentContext` are not being forwarded - which means they are unset.
=> fix: spread parent ComponentContext props
